folio-org/ui-organizations

package.json, src/Accounts/AccountsForm.js, src/Accounts/AccountsView.js, src/Agreements/AgreementsForm.js, src/Agreements/AgreementsView.js, src/ContactInformation/ContactInfoViewGroup/PhoneNumbersView.js, src/ContactInformation/ContactInformationForm.js, src/ContactInformation/ContactInformationView.js, src/ContactPeople/ContactPeopleForm.js, src/ContactPeople/ContactPeopleView.js, src/EdiInformation/EdiInformationForm.js, src/EdiInformation/EdiInformationView.js, src/Interface/InterfaceForm.js, src/Interface/InterfaceView.js, src/Main/Main.js, src/MultiForms/AddressesMF.js, src/MultiForms/EmailsMF.js, src/MultiForms/PhoneNumbersMF.js, src/MultiForms/UrlsMF.js, src/PaneDetails/PaneDetails.js, src/Settings/CategorySettings.js, src/Summary/SummaryForm.js, src/Summary/SummaryView.js, src/Utils/FilterConfig.js, src/Utils/FormatTime.js, src/VendorInformation/VendorInformationForm.js, src/VendorInformation/VendorInformationView.js, src/VendorViews/FormVendor.js, src/VendorViews/ViewVendor.js
The new endpoints are created as part of transition from vendors to organizations and refactoring of the schemas so UI should use them.
https://issues.folio.org/browse/UIORGS-33
Renaming
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …
=> UIORGS-33 Swith to new API (organizations-storage)

src/PaneDetails/PaneDetails.js
revert some functionality after breaking changes
`getCurrencies()` method body was reverted …
=> UIORGS-24 Remove signs '+' and '--' from translation values

translations/ui-organizations/en.json
To change the Settings for the Vendor app into Settings for the Organizations app. This only covers the name change.
https://issues.folio.org/browse/UIORGS-32
change translation values
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …
=> UIORGS-32 Settings UI changes related to Vendor pivot

translations/ui-organizations/en.json
To change the Vendor app into an Organizations app. This only covers the app name and landing page changes. Other portions of this change are covered in other stories
https://issues.folio.org/browse/UIORGS-31
change translation labels …
=> UIORGS-31 App UI changes related to Vendor pivot

translations/ui-organizations/ar.json, translations/ui-organizations/ca.json, translations/ui-organizations/da.json, translations/ui-organizations/de.json, translations/ui-organizations/en_GB.json, translations/ui-organizations/en_SE.json, translations/ui-organizations/en_US.json, translations/ui-organizations/es.json, translations/ui-organizations/es_ES.json, translations/ui-organizations/fr.json, translations/ui-organizations/fr_FR.json, translations/ui-organizations/hu.json, translations/ui-organizations/it_IT.json, translations/ui-organizations/pt_BR.json, translations/ui-organizations/pt_PT.json, translations/ui-organizations/zh_CN.json
=> Update translation strings as of 20190415T231934

src/VendorInformation/VendorInformationView.js
Remove fields, they appeared againg after merge with master and conflicts resolving
https://issues.folio.org/browse/UIORGS-2 …
=> UIORGS-2 remove change arised after merge conflict

src/ContactPeople/ContactPeopleView.css, src/ContactPeople/ContactPeopleView.js
text will wrap such that it dose not overlap adjacent info or bleed outside of border.
https://issues.folio.org/browse/UIORGS-22
use `overflow-wrap: break-word;` css3 property. …
=> UIORGS-22 Contact person area Column width broken

src/Accounts/AccountsForm.js, src/EdiInformation/EdiInformationView.js, translations/ui-organizations/en.json
It needs to be removed asterisks signs from translations
https://issues.folio.org/browse/UIORGS-23
Replaced hardcoded string values with asterisks on translations, added required attiributes
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
=> UIORGS-23 Remove asterisks signs

index.js, package.json, src/Main/Main.js, src/PaneDetails/PaneDetails.js, src/Summary/SummaryForm.js, src/VendorInformation/VendorInformationForm.js, src/VendorViews/FormVendor.js, src/common/constants/sections.js, test/bigtest/interactors/orgSections/AccountsSection.js, test/bigtest/interactors/orgSections/ContactInformationSection.js, test/bigtest/interactors/orgSections/ContactPeopleSection.js, test/bigtest/interactors/orgSections/EdiInformationSection.js, test/bigtest/interactors/orgSections/InterfacesSection.js, test/bigtest/interactors/orgSections/SummarySection.js, test/bigtest/interactors/orgSections/VendorInformationSection.js, test/bigtest/interactors/orgSections/VendorTermsSection.js, test/bigtest/interactors/orgSections/index.js, test/bigtest/interactors/organizationDetails.js, test/bigtest/interactors/organizationEdit.js, test/bigtest/network/configs/organizations.js, test/bigtest/tests/organizationCreate.e2e.js, test/bigtest/tests/organizationDetails.e2e.js, translations/ui-organizations/en.json
To change the create vendor screen into a create organizations screen, to clean up some of the text, and to suppress vendor-specific accordions when they are not needed. 
https://issues.folio.org/browse/UIORGS-3
Renaming, layout change …
=> UIORGS-3 Restructure 'create vendor' screen for organizations

translations/ui-organizations/en.json
To remove empty values, they makes no sense. …
=> UIORGS-31 remove empty translation values

src/Accounts/AccountsForm.js, src/PaneDetails/PaneDetails.js, src/Summary/SummaryForm.js, test/bigtest/interactors/organizationEdit.js, translations/ui-organizations/en.json
To change the edit vendor screen into an edit organizations screen, to clean up some of the text, and to suppress vendor-specific accordions when they are not needed. 
https://issues.folio.org/browse/UIORGS-4
Renaming
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
=> UIORGS-4 Restructure 'edit vendor' screen for organizations

src/Accounts/AccountsView.css, src/Accounts/AccountsView.js, src/Agreements/AgreementsView.js, src/EdiInformation/EdiInformationView.js, src/VendorInformation/VendorInformationView.js, src/VendorViews/ViewVendor.js, src/VendorViews/ViewVendorBlocks.js, test/bigtest/interactors/organizationDetails.js, test/bigtest/tests/organizationDetails.e2e.js, test/bigtest/tests/vendorOrganizationDetails.e2e.js, translations/ui-organizations/en.json
Requirements to blocks order were changed in another ticket and PO brought attention on that at Review.
original ticket - https://issues.folio.org/browse/UIORGS-2
new requirements - https://issues.folio.org/browse/UIORGS-4
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
=> UIORGS-2 fix blocks order

src/Accounts/AccountsForm.js, src/Summary/SummaryForm.js, src/Utils/FilterConfig.js, src/common/constants/index.js, src/common/constants/organization.js, test/bigtest/interactors/organizationEdit.js, test/bigtest/network/factories/organization.js, test/bigtest/tests/organizationCreate.e2e.js, translations/ui-organizations/en.json
UI operates only with statuses defined in back-end enum from corresponding ticket [MODORGS-25.](https://issues.folio.org/browse/MODORGS-25)
https://issues.folio.org/browse/UIORGS-53
In order to ensure consistency, the `organization.status` field should be an enumeration with the following values:
"Pending",
"Inactive",
"Active"
Ideally all of the PRs …
=> UIORGS-53 Make org status consistent with back-end

src/ContactPeople/ContactPerson/ContactPersonDetails/ContactPersonDetails.js, translations/ui-organizations/en.json
A new form needs to be created that will allow the user to create or add a "contact person" to an organization.
https://issues.folio.org/browse/UIORGS-43
new translations …
=> UIORGS-43 contact person on org view - fix translations

index.js, package.json, src/ContactPeople/ContactPeopleForm.js, src/PaneDetails/PaneDetails.js, src/VendorViews/FormVendor.js, src/contacts/ContactsContainer.js, src/contacts/ContactsEditContainer.js, src/contacts/ContactsView.js, src/contacts/index.js, translations/ui-organizations/en.json
Purpose: to handle transition from Edit Organizations form's contacts section list deeper - to manage contacts component.
https://issues.folio.org/browse/UIORGS-45
Created routes wrapper for contacts, to handle urls like `/organizations/:orgId/contacts/***` and `/organizations/contacts/***` (in case of new org)
Ideally all of the PRs involved in breaking …
=> UIORGS-45 Contacts wrapper component

src/Accounts/AccountsView.js
fix translation
https://issues.folio.org/browse/UIORGS-2
fix translation id
While it's …
=> UIORGS-2 orgs details view - fix translation

src/PaneDetails/PaneDetails.js, translations/ui-organizations/en.json
it needs to change buttons labels
https://issues.folio.org/browse/UIORGS-59
changed buttons label, renamed translations keys …
=> UIORGS-59 Change Create/Update Organizations buttons to [Save]

CHANGELOG.md, package.json
Initial release
https://issues.folio.org/browse/UIORGS-49 …
=> UIORGS-49 - Release v1.0.0

translations/ui-organizations/ar.json, translations/ui-organizations/ca.json, translations/ui-organizations/da.json, translations/ui-organizations/de.json, translations/ui-organizations/en_GB.json, translations/ui-organizations/en_SE.json, translations/ui-organizations/en_US.json, translations/ui-organizations/es.json, translations/ui-organizations/es_419.json, translations/ui-organizations/es_ES.json, translations/ui-organizations/fr.json, translations/ui-organizations/fr_FR.json, translations/ui-organizations/hu.json, translations/ui-organizations/it_IT.json, translations/ui-organizations/pt_BR.json, translations/ui-organizations/pt_PT.json, translations/ui-organizations/zh_CN.json
=> Update translation strings as of 20190426T133506

src/Main/Main.js
https://issues.folio.org/browse/UIORGS-38
avoid undefined in cql …
=> UIORGS-38 Problem with vendor lookup when creating a PO

src/ContactPeople/ContactPeopleForm.js, src/Main/Main.js, src/common/resources/contacts.js, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-50
purpose: add possibility to search and select contacts
use find-contact plugin …
=> UIORGS-50 Modal Select Contact with SearchAndSort implementation

translations/ui-organizations/ar.json, translations/ui-organizations/ca.json, translations/ui-organizations/da.json, translations/ui-organizations/de.json, translations/ui-organizations/en_GB.json, translations/ui-organizations/en_SE.json, translations/ui-organizations/en_US.json, translations/ui-organizations/es.json, translations/ui-organizations/es_419.json, translations/ui-organizations/es_ES.json, translations/ui-organizations/fr.json, translations/ui-organizations/fr_FR.json, translations/ui-organizations/hu.json, translations/ui-organizations/it_IT.json, translations/ui-organizations/pt_BR.json, translations/ui-organizations/pt_PT.json, translations/ui-organizations/zh_CN.json
=> Update translation strings as of 20190501T184815

translations/ui-organizations/ar.json
=> Update translation strings as of 20190502T124851

src/ContactPeople/ContactPeopleForm.js, src/ContactPeople/ContactPeopleList.js, src/Main/Main.js, src/VendorViews/FormVendor.js, src/common/resources/index.js, src/common/resources/organization.js, src/contacts/ContactsContainer.js, src/contacts/ViewContact/ViewContact.js, src/contacts/ViewContact/ViewContactContainer.js, src/contacts/ViewContact/util.js, test/bigtest/interactors/ConfirmationModal.js, test/bigtest/interactors/ContactList.js, test/bigtest/interactors/ViewContact.js, test/bigtest/interactors/organizationEdit.js, test/bigtest/tests/organizationCreate.e2e.js, test/bigtest/tests/organizationDetails.e2e.js, test/bigtest/tests/organizationEdit.e2e.js, test/bigtest/tests/viewContact.e2e.js, translations/ui-organizations/en.json
Un-assign contact function. User has to be able un-assign contact from View Contact screen or from Edit Organization form - Contact People accordion.
https://issues.folio.org/browse/UIORGS-52
Code related to displaying of Contacts list was moved to a separate functional component ContactPeopleList
Ideally all of the PRs involved in breaking changes would …
=> UIORGS-52 unassign contact, 2 places

src/contacts/ViewContact/ViewContact.js, src/contacts/ViewContact/ViewContactContainer.js, src/contacts/ViewContact/util.js, test/bigtest/interactors/ViewContact.js, test/bigtest/tests/viewContact.e2e.js, translations/ui-organizations/en.json
User should be able to delete contact.
https://issues.folio.org/browse/UIORGS-48
show action button in dropdown, confirmation modal on click and call delete contact API on confirm.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
=> UIORGS-48 Delete contact action

src/ContactPeople/ContactPeopleForm.js, src/ContactPeople/ContactPeopleList.js
There is a bug when user tries to add new contact and its data isn't fetched from back-end. Also added check to unique of selected contact.
https://issues.folio.org/browse/UIORGS-50
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
=> UIORGS-50 fix add contact data fetch and uniquiness

src/common/utils/category.js, src/contacts/EditContact/AddressForm/AddressForm.js, src/contacts/EditContact/ContactDetailsForm/ContactDetailsForm.js, src/contacts/EditContact/ContactDetailsForm/EmbeddedContactForm.js, src/contacts/EditContact/EditContact.js, src/contacts/EditContact/EditContactContainer.js, src/contacts/EditContact/EmailForm/EmailForm.js, src/contacts/EditContact/PhoneForm/PhoneForm.js, src/contacts/EditContact/UrlForm/UrlForm.js
Fix categories and isPrimary fields
While it's …
=> UIORGS-47 Fix categories and isPrimary

src/ContactPeople/ContactPeopleList.js
https://issues.folio.org/browse/UIORGS-63
change url
While it's helpful for reviewers to …
=> UIORGS-63 fix url for new button on add contacts modal

src/common/resources/contacts.js, src/contacts/ViewContact/ViewContactContainer.js
Fix of save and refresh of resource contact
Basically, we don't need `path` as function, it works well as interpolated string
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
=> UIORGS-47 fix of error message on successful contact save

src/contacts/ContactsContainer.js, src/contacts/EditContact/EditContact.js, src/contacts/EditContact/EditContactContainer.js, src/contacts/ViewContact/util.js, test/bigtest/interactors/CreateContact.js, test/bigtest/network/configs/contacts.js, test/bigtest/tests/createContact.e2e.js, test/bigtest/tests/editContact.e2e.js, translations/ui-organizations/en.json
Add save functionality for editing contact form …
=> UIORGS-47 Add Save functionality

src/contacts/ViewContact/ViewContactContainer.js, translations/ui-organizations/en.json
missing word `this` in message
https://issues.folio.org/browse/UIORGS-52
While it's …
=> UIORGS-52 missing word on message

src/common/resources/contacts.js, src/contacts/ContactsContainer.js, src/contacts/EditContact/EditContact.js, src/contacts/EditContact/EditContactContainer.js, src/contacts/EditContact/util.js, src/contacts/ViewContact/ViewContactContainer.js, src/contacts/ViewContact/util.js
Can't close out of contact person detail view.
https://issues.folio.org/browse/UIORGS-64
Instead of `history.goBack()` to use a specific paths.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
=> UIORGS-64 fix close out of contact person detail view

translations/ui-organizations/pt_BR.json
=> Update translation strings as of 20190508T134606

src/Main/Main.js, src/PaneDetails/PaneDetails.js, src/Utils/PhoneTypes.js, src/common/utils/dropdown.js, src/contacts/EditContact/AddressForm/AddressForm.js, src/contacts/EditContact/ContactDetailsForm/ContactDetailsForm.js, src/contacts/EditContact/ContactDetailsForm/EmbeddedContactForm.js, src/contacts/EditContact/EditContact.js, src/contacts/EditContact/EmailForm/EmailForm.js, src/contacts/EditContact/PhoneForm/PhoneForm.js, src/contacts/EditContact/UrlForm/UrlForm.js, src/contacts/EditContact/constants.js
Add dataOptions to `Select` fields
While it's …
=> UIORGS-47 Add dropdown lists to contact form

src/ContactPeople/ContactPeopleList.js
https://issues.folio.org/browse/UIORGS-51
Provide the ability to add multiple contacts at once from `plugin-find-contact` to organization …
=> UIORGS-51 Select and add multiple contacts at once

src/Interface/constants.js, test/bigtest/interactors/Interfaces/InterfaceList.js, test/bigtest/tests/organizationEdit.e2e.js
It needs user to be able unassign interface from edit organization form
https://issues.folio.org/browse/UIORGS-57
provided button for this functionality
added callback for deleting selected interface from form values by button clicking …
=> UIORGS-57 un-assign interface from organization edit

index.js, package.json, src/Interface/InterfaceView/InterfaceView.js, src/Interface/InterfacesList.js, src/Interface/InterfacesListContainer.js, src/Interface/utils.js, src/Main/Main.js, src/VendorViews/FormVendor.js, src/common/resources/interfaces.js, src/common/styles/subHeadings.css, src/interfaces/EditInterface/EditInterface.css, src/interfaces/EditInterface/EditInterface.js, src/interfaces/EditInterface/EditInterfaceContainer.js, src/interfaces/EditInterface/const.js, src/interfaces/EditInterface/index.js, src/interfaces/EditInterface/util.js, src/interfaces/InterfaceContainer.js, src/interfaces/constants.js, src/interfaces/index.js, test/bigtest/helpers/setup-application.js, test/bigtest/interactors/Interfaces/InterfaceEdit.js, test/bigtest/interactors/index.js, test/bigtest/network/boot.js, test/bigtest/network/configs/interfaces.js, test/bigtest/tests/createInterface.e2e.js, test/bigtest/tests/editInterface.e2e.js, test/bigtest/tests/organizationCreate.e2e.js, translations/ui-organizations/en.json
Purpose: Allow users and other applications to manage interfaces and assign them to organizations.
https://issues.folio.org/browse/UIORGS-34 …
=> UIORGS-34 Create and Edit interface

src/Interface/InterfaceView/InterfaceView.js, src/common/constants/index.js, src/common/constants/interfaces.js, src/interfaces/EditInterface/EditInterface.js, src/interfaces/EditInterface/util.js, test/bigtest/interactors/Interfaces/InterfaceEdit.js, test/bigtest/network/configs/interfaces.js, test/bigtest/network/configs/organizations.js, test/bigtest/network/configs/util.js, test/bigtest/tests/editInterface.e2e.js, translations/ui-organizations/en.json
As a librarian 
I want to specify the interface type on an Organization record
So that anyone on my staff has a clear understanding of which interface to use to access what they need.
https://issues.folio.org/browse/UIORGS-55
We use simple Select component, as on provided mockups in the ticket.
Ideally all of the PRs involved in breaking changes would be …
=> UIORGS-55 ADd Type field to Edit interface

src/contacts/EditContact/ContactDetailsForm/EmbeddedContactForm.js, src/contacts/EditContact/EditContact.js
Fix categories dropdown
add prop `itemToString` to Categories field
While it's helpful …
=> UIORGS-47 Fix categories dropdown

src/common/utils/createItem.js, src/contacts/EditContact/EditContactContainer.js, src/interfaces/EditInterface/EditInterfaceContainer.js
it needs to redirect to the edit organization page in case if new interface/contact wasn't been created
https://issues.folio.org/browse/UIORGS-70
checked id new item, if it equals undefined then redirect to edit organization page …
=> UIORGS-70 Fix Close new interface/contact button redirect

src/interfaces/EditInterface/EditInterface.css
There is an extra caret, that doesn't needed in multiple select case
https://issues.folio.org/browse/UIORGS-55 …
=> UIORGS-55 we dont need extra caret in select[multiple]

translations/ui-organizations/zh_CN.json
=> Update translation strings as of 20190520T224011

package.json, src/ContactPeople/ContactPeopleForm.js, src/ContactPeople/ContactPeopleList.js, src/Interface/InterfacesListContainer.js, src/Interface/utils.js, src/Main/Main.js, src/VendorViews/FormVendor.js, src/common/utils/index.js, src/common/utils/mutatorGet.js, test/bigtest/tests/organizationEdit.e2e.js
Contacts list is not refreshed on Or Edit screen after contact is edited. …
=> UIORGS-47 fix refresh contacts list on org edit

src/Main/Main.js, src/Utils/FilterConfig.js, translations/ui-organizations/en.json
To be able to identify Vendors in the list of organizations search results
https://issues.folio.org/browse/UIORGS-72
Add “Is Vendor” column to Organizations search results and add Filter for "Is Vendor"
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
=> UIORGS-72 Add vendor column and Filter Is Vendor

translations/ui-organizations/ar.json, translations/ui-organizations/ca.json, translations/ui-organizations/da.json, translations/ui-organizations/de.json, translations/ui-organizations/en_GB.json, translations/ui-organizations/en_SE.json, translations/ui-organizations/en_US.json, translations/ui-organizations/es.json, translations/ui-organizations/es_419.json, translations/ui-organizations/es_ES.json, translations/ui-organizations/fr.json, translations/ui-organizations/fr_FR.json, translations/ui-organizations/hu.json, translations/ui-organizations/it_IT.json, translations/ui-organizations/pt_BR.json, translations/ui-organizations/pt_PT.json, translations/ui-organizations/zh_CN.json
=> Update translation strings as of 20190603T125055

src/Settings/SettingsPage.js
display settings in correct way
remove unused permission restriction
While it's helpful …
=> fix settings permission

src/PaneDetails/PaneDetails.js, src/VendorViews/ViewVendor.js, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-65
https://issues.folio.org/browse/UIORGS-66
remove title attribute …
=> UIORGS-65 UIORGS-66 Inappropriate tooltip text on save/edit buttons

package.json, src/Main/Main.js
Permissions problems with ui-organizations
https://issues.folio.org/browse/UIORGS-76
Fix permission name for `Organizations: all permissions for Create, View, Edit and Delete organizations`
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
=> UIORGS-76 Permissions problems with ui-orgs

.eslintrc, CHANGELOG.md, package.json
Release of v1.2.0
https://issues.folio.org/browse/UIORGS-77 …
=> Release v1.2.0

package.json
Permissions problems with ui-organizations
https://issues.folio.org/browse/UIORGS-76
add permissions required to call services apart from mod-organizations-storage
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
=> UIORGS-76 Permissions problems

translations/ui-organizations/ar.json
=> Update translation strings as of 20190627T152539

package.json
It's a PR to enable coverage
Also added missing interface and permission of users
https://issues.folio.org/browse/UIORGS-76 …
=> UIORGS-76 add users permission and interface, enable coverage

src/VendorViews/ViewVendor.js, test/bigtest/helpers/setup-application.js, test/bigtest/network/config.js, test/bigtest/network/configs/users.js, test/bigtest/network/factories/user.js, test/bigtest/network/models/user.js, test/bigtest/tests/OrganizationDetails/OrganizationDetailsNoEdit.e2e.js
https://issues.folio.org/browse/UIORGS-81
some unit tests + fix network for `ViewMetaData` component
permissions property in setupApplication can be used to define user perms …
=> UIORGS-81 test permissions with BigTest

package.json
To provide smooth build process on the time of releasing new versions of okapi interfaces
https://issues.folio.org/browse/UIORGS-80 …
=> UIORGS-80 update okapi interface versions

src/ContactInformation/ContactInfoFormGroup/AddressInfo.js, src/ContactInformation/ContactInfoFormGroup/EmailAddresses.js, src/ContactInformation/ContactInfoFormGroup/PhoneNumbers.js, src/ContactInformation/ContactInfoFormGroup/Urls.js, src/ContactInformation/ContactInfoFormGroup/createAddNewItem.js, src/ContactInformation/ContactInformationForm.js, src/PaneDetails/PaneDetails.js, src/VendorViews/FormVendor.js, translations/ui-organizations/en.json
Populate language fields initially with Organization "Default language"
https://issues.folio.org/browse/UIORGS-11 …
=> UIORGS-11 use default language

translations/ui-organizations/ar.json, translations/ui-organizations/ca.json, translations/ui-organizations/da.json, translations/ui-organizations/de.json, translations/ui-organizations/en_GB.json, translations/ui-organizations/en_SE.json, translations/ui-organizations/en_US.json, translations/ui-organizations/es.json, translations/ui-organizations/es_419.json, translations/ui-organizations/es_ES.json, translations/ui-organizations/fr.json, translations/ui-organizations/fr_FR.json, translations/ui-organizations/hu.json, translations/ui-organizations/it_IT.json, translations/ui-organizations/pt_BR.json, translations/ui-organizations/pt_PT.json, translations/ui-organizations/zh_CN.json
=> Update translation strings as of 20190801T134041

src/Main/Main.js, src/VendorViews/FormVendor.js, src/VendorViews/ViewVendor.js, test/bigtest/interactors/index.js, test/bigtest/interactors/organizationDetails.js, test/bigtest/network/configs/organizations.js, test/bigtest/tests/organizationDetails.e2e.js, translations/ui-organizations/en.json
Organizations has a "Delete" button that is in an odd place and deletes the entire Organization without any confirmation (though the "unsaved changes" modal may flash briefly. We need to move the button and add a confirmation modal
https://issues.folio.org/browse/UIORGS-74
Add menu on header and add confirmation modal when tried delete record.
Ideally …
=> Uiorgs 74 reconfigure the organizations

src/ContactInformation/ContactInfoFormGroup/AddressInfo.js, src/ContactInformation/ContactInfoFormGroup/EmailAddresses.js, src/ContactInformation/ContactInfoFormGroup/FieldIsPrimary.js, src/ContactInformation/ContactInfoFormGroup/PhoneNumbers.js, src/ContactInformation/ContactInfoFormGroup/Urls.js, src/ContactInformation/ContactInfoFormGroup/createAddNewItem.js, src/ContactInformation/ContactInformationForm.js, src/ContactPeople/ContactPeopleForm.js, src/PaneDetails/PaneDetails.js, src/VendorViews/FormVendor.js, test/bigtest/interactors/AutoSuggestListInteractor.js, test/bigtest/interactors/CheckboxInteractor.js, test/bigtest/interactors/TextFieldInteractor.js, test/bigtest/interactors/index.js, test/bigtest/interactors/organizationEdit.js, test/bigtest/tests/organizationCreate.e2e.js
Changes to primary address/email/phone_number/urls
https://issues.folio.org/browse/UIORGS-18
I've used `Card` common component to display checkbox. IMHO, `Radiobutton` is a wrong here, since we should control boolean property of every record.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> UIORGS-18 isPrimary for contact info records

package.json, src/Interface/InterfaceView/InterfaceView.js, src/Interface/InterfacesViewContainer.js, src/common/resources/interfaces.js, src/common/utils/getResourceData.js, src/common/utils/index.js, src/interfaces/EditInterface/EditInterfaceContainer.js, src/interfaces/EditInterface/util.js, src/interfaces/ViewInterface/ViewInterface.js, src/interfaces/ViewInterface/ViewInterfaceContainer.js, test/bigtest/interactors/Interfaces/InterfacePane.js, test/bigtest/network/factories/interface.js, test/bigtest/tests/viewInterface.e2e.js
Vendor/Organization app | View Detail Record | Interface > password display
https://issues.folio.org/browse/UIORGS-39 …
=> UIORGS-39 Show creds button on View Interface

src/Interface/InterfaceView/InterfaceView.js, src/Interface/InterfaceView/InterfaceViewContainer.js, src/Interface/InterfaceView/index.js, src/Interface/InterfacesViewContainer.js, src/common/resources/interfaces.js
Ability to show password on View Organization details pane in three-panes-layout
https://issues.folio.org/browse/UIORGS-39 …
=> UIORGS-39 show password on vendor details

src/ContactInformation/ContactInformationView.js, src/ContactPeople/ContactPerson/ContactPerson.js, src/common/utils/hydrateContactInfo.js, src/common/utils/index.js, src/contacts/EditContact/ContactDetailsForm/EmbeddedContactForm.js, src/contacts/EditContact/EditContact.js
show the primary first in the view, Regardless of the order of the information in the edit form
https://issues.folio.org/browse/UIORGS-39?focusedCommentId=57640&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-57640
https://issues.folio.org/browse/UIORGS-18
Ideally all of the PRs involved in breaking changes would be merged …
=> UIORGS-18 sort primary info on top

src/ContactInformation/ContactInfoFormGroup/AddressInfo.js, src/ContactInformation/ContactInfoFormGroup/ContactInfoCard.css, src/ContactInformation/ContactInfoFormGroup/EmailAddresses.js, src/ContactInformation/ContactInfoFormGroup/PhoneNumbers.js, src/ContactInformation/ContactInfoFormGroup/Urls.js
While testing was discovered an issue with overflow and multiselect of categories was unable to be used. 
https://issues.folio.org/browse/UIORGS-18 …
=> UIORGS-18 fix categories overflow

translations/ui-organizations/ar.json, translations/ui-organizations/ca.json, translations/ui-organizations/da.json, translations/ui-organizations/de.json, translations/ui-organizations/en_GB.json, translations/ui-organizations/en_SE.json, translations/ui-organizations/en_US.json, translations/ui-organizations/es.json, translations/ui-organizations/es_419.json, translations/ui-organizations/es_ES.json, translations/ui-organizations/fr.json, translations/ui-organizations/fr_FR.json, translations/ui-organizations/hu.json, translations/ui-organizations/it_IT.json, translations/ui-organizations/pt_BR.json, translations/ui-organizations/pt_PT.json, translations/ui-organizations/zh_CN.json
=> Update translation strings as of 20190809T200806

src/Main/Main.js, src/VendorViews/ViewVendor.js, translations/ui-organizations/en.json
turn on tags for view organization
Turn on tags for View organization.
https://issues.folio.org/browse/UIORGS-13
Use `withTags` HOC from stripes-smart-components.
=> UIORGS-13 Assign tags to Organization Records

translations/ui-organizations/ar.json
=> Update translation strings as of 20190812T142216

src/Interface/InterfaceView/InterfaceView.js, src/PaneDetails/PaneDetails.js, test/bigtest/interactors/organizationEdit.js, test/bigtest/tests/organizationEdit.e2e.js
Remove button if it's clicked
A small fix to layout for better UX, hide button when it's clicked, fix required space for button.
https://issues.folio.org/browse/UIORGS-39 …
=> UIORGS-39 fix layout

package.json
It's a part 1 - re-work permissions in Organization app, so they goes to back-end and we can assign them to user. After that I'll test the rest changes and tests.
https://issues.folio.org/browse/UIORGS-79
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
=> UIORGS-79 re-work permissions

package.json
add perms for tags, categories in settings
https://issues.folio.org/browse/UIORGS-79 …
=> UIORGS-79 fix to perms

src/EdiInformation/EdiInformationForm.js, src/Utils/TogglePassword.js
fix for Interface: Username and Password auto-populates with saved username/password
https://issues.folio.org/browse/UIORGS-95
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
=> UIORGS-95 disable autocomplete for passwords

src/VendorViews/ViewVendor.js
To resolve a bug ticket we need to make a release of ui-organizations. However, to prevent the whole chain of back-end releases (mod-orgs, mod-orders, mod-invoice etc.) we need to check the version of okapi interface to support tags. It will be done in `organizations-storage.organizations` 2.1 or later.
https://issues.folio.org/browse/UIORGS-96
Ideally …
=> UIORGS-96 Hide tags switch for inappropriate version of okapi interface

src/Main/Main.js, src/PaneDetails/PaneDetails.js, src/VendorInformation/VendorInformationForm.js, src/VendorInformation/VendorInformationView.js
https://issues.folio.org/browse/UIORGS-97
use standard list from stripes-components …
=> UIORGS-97 Update the currency list for vendors to rely on the standard currency list

translations/ui-organizations/ar.json
=> Update translation strings as of 20190828T124751

src/VendorInformation/VendorInformationForm.js, test/bigtest/interactors/orgSections/ContactPeopleSection.js, test/bigtest/tests/organizationDetails.e2e.js, test/bigtest/tests/organizationEdit.e2e.js
https://issues.folio.org/browse/UIORGS-97 …
=> UIORGS-97 vendor currency field - case insensitive filter

src/Interface/InterfacesList.js, src/Interface/InterfacesListContainer.js, src/VendorViews/FormVendor.js, src/VendorViews/ViewVendor.js, test/bigtest/interactors/orgSections/ContactPeopleSection.js, test/bigtest/interactors/organizationDetails.js, test/bigtest/interactors/organizationEdit.js, test/bigtest/tests/organizationCreate.e2e.js, test/bigtest/tests/organizationDetails.e2e.js, test/bigtest/tests/organizationEdit.e2e.js
some code clean-up after usage of `PluginFindRecord`
https://issues.folio.org/browse/UIORGS-87 …
=> UIORGS-87 code clean-up

src/VendorInformation/VendorInformationForm.js
https://issues.folio.org/browse/UIORGS-97 …
=> UIORGS-97 fix currency field search

src/Main/OrganizationsSearchConfig.js
To fix search query with `Keyword` option.
https://issues.folio.org/browse/UIOR-367
The search query is failing due to incorrect format of `queryTemplate`. So to fix this we use a common function to generate queryTemplate.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
=> UIOR-367 fix search query

CHANGELOG.md, package.json, src/VendorViews/ViewVendor.js
https://issues.folio.org/browse/UIORGS-105 …
=> Release v1.5.0

translations/ui-organizations/it_IT.json
=> Update translation strings as of 20190918T144452

src/ContactPeople/ContactPeopleForm.js, src/ContactPeople/ContactPeopleList.js, src/Interface/InterfacesList.js, src/Interface/InterfacesListContainer.js, src/Interface/constants.js, src/Main/Main.js, src/Summary/SummaryView.js
ACQ Apps: MCL column width updates
https://issues.folio.org/browse/STCOM-590
Remove `columnWidths` prop from MCL …
=> STCOM-590 ACQ Apps: MCL column width updates

src/Interface/InterfaceView/InterfaceView.js, test/bigtest/tests/viewInterface.e2e.js, translations/ui-organizations/en.json
Just having a "Show Credentials" button and not showing anything else
https://issues.folio.org/browse/UIORGS-99 …
=> UIORGS-99 show labels only after button Show is clicked

src/common/constants/organization.js, translations/ui-organizations/en.json
Fix capitalization of phrases in ui-organizations
https://issues.folio.org/browse/UIORGS-84 …
=> UIORGS-84 Fix capitalization of phrases

src/Summary/SummaryForm.js, test/bigtest/interactors/ViewContact.js, test/bigtest/interactors/organizationEdit.js, test/bigtest/network/configs/categories.js, test/bigtest/network/configs/contacts.js, test/bigtest/network/configs/interfaces.js, test/bigtest/network/configs/organizations.js, test/bigtest/network/configs/users.js, test/bigtest/network/configs/util.js, test/bigtest/tests/viewContact.e2e.js
use BigTest mirage handlers from common repo …
=> use common mirage handlers

package.json, src/ContactPeople/ContactPerson/ContactPersonItem/ContactPersonItem.js, src/VendorViews/ViewVendor.js, src/contacts/EditContact/ContactDetailsForm/ContactDetailsForm.js, src/contacts/EditContact/ContactDetailsForm/EmbeddedContactForm.js
=> bump stripes deps

src/Accounts/AccountsForm.js, src/Accounts/AccountsView.js, src/EdiInformation/EdiInformationView.js, src/Main/Main.js, src/Main/OrganizationsFilter.js, src/Main/constants.js, src/VendorInformation/VendorInformationForm.js, src/VendorInformation/VendorInformationView.js, src/VendorViews/ViewVendorBlocks.js, src/common/constants/organization.js, test/bigtest/interactors/orgSections/AccountsSection.js, translations/ui-organizations/en.json
Add  translatable payment methods options and labels
- enum  payment methods options - [schema](https://github.com/folio-org/acq-models/blob/master/mod-orgs/schemas/account.json#L25)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …
=> UIORGS-84 Add translatable payment methods options

translations/ui-organizations/zh_CN.json
=> Update translation strings as of 20191022T162142

src/Accounts/AccountsForm.js, src/Agreements/AgreementsForm.js, src/EdiInformation/EdiInformationForm.js, src/Summary/SummaryForm.js, src/VendorInformation/VendorInformationForm.js
FOLIO is adopting a four column layout for Edit forms. This will reduce the amount of scrolling required in longer records.
The Organization form fields should be laid out as they are in the view pane
https://issues.folio.org/browse/UIORGS-115
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> UIORGS-115 Update Org layout for create/edit

src/PaneDetails/PaneDetails.js, translations/ui-organizations/en.json
Organization: Update "Save and close" and "Cancel" Buttons - UX
https://issues.folio.org/browse/UIORGS-114 …
=> UIORGS-114 Organization: Update "save and close" and "Cancel" Buttons - UX

translations/ui-organizations/it_IT.json, translations/ui-organizations/ru.json
=> Update translation strings as of 20191115T154823

src/Interface/InterfaceView/InterfaceView.js, translations/ui-organizations/en.json
hide creds button
https://issues.folio.org/browse/UIORGS-86 …
=> UIORGS-86 hide creds button

CHANGELOG.md, index.js, package.json, src/ContactPeople/ContactPeopleView.js, src/ContactPeople/ContactPeopleViewContainer.js, src/ContactPeople/index.js, src/VendorViews/ViewVendor.js, test/bigtest/interactors/orgSections/ContactPeopleSection.js, test/bigtest/interactors/organizationDetails.js, test/bigtest/tests/organizationDetails.e2e.js, translations/ui-organizations/en.json
Viewing organization information is difficult when the contact people accordion is open. Contact people are difficult to distinguish between as their information seems to run into each other. Creating more separation between contacts would make the app much more usable.
https://issues.folio.org/browse/UIORGS-122
Ideally all of the PRs involved in breaking …
=> UIORGS-122 Organization view pane: Update contact people view

src/common/components/ButtonIsPrimary/ButtonIsPrimary.css, src/common/components/ButtonIsPrimary/ButtonIsPrimary.js, src/common/components/ButtonIsPrimary/index.js, src/common/components/index.js, src/contacts/EditContact/EmailForm/EmailForm.js, src/contacts/EditContact/PhoneForm/PhoneForm.js, src/contacts/EditContact/UrlForm/UrlForm.js
https://issues.folio.org/browse/UIORGS-124 …
=> UIORGS-124 use buttons instead of checkboxes to select primary info

src/contacts/ViewContact/ContactEmails/ContactEmails.js, src/contacts/ViewContact/ContactPhoneNumbers/ContactPhoneNumbers.js, src/contacts/ViewContact/ContactUrls/ContactUrls.js
Remove the hover effect from the table rows as none of these rows are clickable
https://issues.folio.org/browse/UIORGS-123 …
=> UIORGS-123 Disable hover effect

CHANGELOG.md, src/Interface/InterfacesListContainer.js, src/Main/Main.js, src/VendorViews/FormVendor.js, src/interfaces/EditInterface/EditInterfaceContainer.js, src/interfaces/EditInterface/util.js, test/bigtest/tests/createInterfaceNoOrg.e2e.js
Assign a newly created interface to an Organization record
To support this some refactoring to resource loading of interfaces was required.
https://issues.folio.org/browse/UIORGS-89
call assign after saving of new interface. Works only for edit org.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> UIORGS-89 Assign a newly created interface to an Organization

translations/ui-organizations/fr_FR.json, translations/ui-organizations/it_IT.json, translations/ui-organizations/zh_CN.json
=> Update translation strings as of 20200109T152437

src/Organizations/OrganizationDetails/OrganizationDetails.js, src/Organizations/OrganizationDetails/OrganizationDetailsContainer.js
https://issues.folio.org/browse/UIORGS-130 …
=> UIORGS-130 TECH-DEBT refactor Organizations list to not use SearchAndSort - tags

package.json, src/Organizations/OrganizationDetails/OrganizationEDIInfo/OrganizationEDIInfo.js, src/Organizations/OrganizationsList/OrganizationsList.js, src/Organizations/OrganizationsList/OrganizationsListContainer.js, src/Organizations/OrganizationsList/OrganizationsListSearchConfig.js
https://issues.folio.org/browse/UIORGS-130 …
=> UIORGS-130 final

src/Organizations/OrganizationForm/OrganizationEDIInfoForm/OrganizationEDIInfoForm.js
https://issues.folio.org/browse/UIORGS-127 …
=> UIORGS-127 EDI schedule days shown incorrectly

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIORGS-143 …
=> UIORGS-143 Update settings permission label

CHANGELOG.md, src/Organizations/OrganizationsList/OrganizationsList.js, src/Organizations/OrganizationsList/OrganizationsListContainer.js, src/common/resources/organization.js, test/bigtest/interactors/organizationsList.js, test/bigtest/tests/organizationsList.e2e.js
Change the Organizations default filters to be empty, so no results are loaded
https://issues.folio.org/browse/UIORGS-110 …
=> UIORGS-110 Change the Organizations default filters to be empty

CHANGELOG.md, src/Organizations/OrganizationCreate/OrganizationCreate.js, src/Organizations/OrganizationEdit/OrganizationEdit.js, src/Organizations/OrganizationForm/OrganizationForm.js, src/Organizations/OrganizationForm/asyncValidate.js, src/Organizations/handleSaveErrorResponse.js, src/common/resources/organization.js, translations/ui-organizations/en.json
Organization codes should be unique. So we user should get async validation at the blur code field event. As well as we display error messages on Save button click
https://issues.folio.org/browse/UIORGS-129
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
=> UIORGS-129 Organization codes should be unique

translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-129 …
=> UIORGS-129 change validation message

translations/ui-organizations/ar.json, translations/ui-organizations/ca.json, translations/ui-organizations/da.json, translations/ui-organizations/de.json, translations/ui-organizations/en_GB.json, translations/ui-organizations/en_SE.json, translations/ui-organizations/en_US.json, translations/ui-organizations/es.json, translations/ui-organizations/es_419.json, translations/ui-organizations/es_ES.json, translations/ui-organizations/fr.json, translations/ui-organizations/fr_FR.json, translations/ui-organizations/he.json, translations/ui-organizations/hu.json, translations/ui-organizations/it_IT.json, translations/ui-organizations/ja.json, translations/ui-organizations/pt_BR.json, translations/ui-organizations/pt_PT.json, translations/ui-organizations/ru.json, translations/ui-organizations/zh_CN.json, translations/ui-organizations/zh_TW.json
=> Update translation strings as of 20200203T164535

CHANGELOG.md, src/Organizations/OrganizationsList/OrganizationsListContainer.js, src/Organizations/OrganizationsList/OrganizationsListFilter/OrganizationsListFilterConfig.js, src/Organizations/OrganizationsList/OrganizationsListFilter/constants.js
https://issues.folio.org/browse/UIORGS-147 …
=> UIORGS-147 Country filter not working

CHANGELOG.md, src/Organizations/OrganizationCreate/OrganizationCreate.js, src/Organizations/OrganizationEdit/OrganizationEdit.js, src/Organizations/OrganizationsList/OrganizationsList.js, src/common/constants/index.js, src/common/constants/routes.js, src/contacts/ContactsContainer.js, test/bigtest/tests/OrganizationDetails/OrganizationDetailsNoEdit.e2e.js, test/bigtest/tests/noPermissions/noDeletePermission.e2e.js, test/bigtest/tests/noPermissions/noEditPermission.e2e.js, test/bigtest/tests/organizationDetails.e2e.js, test/bigtest/tests/vendorOrganizationDetails.e2e.js
https://issues.folio.org/browse/ERM-722 …
=> ERM-722 fix View org details route - revert to the previous url

package.json, src/Organizations/OrganizationsList/OrganizationsListContainer.js, test/bigtest/index.js
=> fix spinner on search field

index.js, src/contacts/ContactsContainer.js, src/interfaces/InterfaceContainer.js, test/bigtest/interactors/organizationsList.js
=> use common calout context

CHANGELOG.md, package.json, src/Organizations/OrganizationDetails/OrganizationDetailsContainer.js, src/Organizations/OrganizationsList/OrganizationsListContainer.js
https://issues.folio.org/browse/UIORGS-153 …
=> Release v2.0.0

index.js, package.json, src/Utils/PhoneTypes.js, src/contacts/ContactsContainer.js, src/contacts/index.js, src/interfaces/InterfaceContainer.js, src/interfaces/index.js
=> fix build is failing

CHANGELOG.md, src/Organizations/OrganizationForm/OrganizationContactInfoForm/ContactInfoFormGroup/EmailAddresses.js, src/Organizations/OrganizationForm/OrganizationContactInfoForm/ContactInfoFormGroup/PhoneNumbers.js, src/Organizations/OrganizationForm/OrganizationContactInfoForm/ContactInfoFormGroup/Urls.js, src/Organizations/OrganizationForm/OrganizationEDIInfoForm/OrganizationEDIInfoForm.js, src/common/components/AddressInfo/AddressInfo.js, src/common/utils/hydrateContactInfo.js
Country codes are handled inconsistently in organization vs. contact addresses.
Requirement to display country label instead of code
https://issues.folio.org/browse/UIORGS-155 …
=> UIORGS-155 display country label instead of code

src/ContactPeople/ContactPerson/ContactPersonDetails/ContactPersonDetails.js, src/ContactPeople/ContactPerson/ContactPersonEmails/ContactPersonEmails.js, src/ContactPeople/ContactPerson/ContactPersonPhones/ContactPersonPhones.js, src/ContactPeople/ContactPerson/ContactPersonURLs/ContactPersonURLs.js, src/Organizations/OrganizationDetails/OrganizationSummary/OrganizationSummary.js, src/common/utils/hydrateContactInfo.js, src/contacts/ViewContact/ContactDetails/ContactDetails.js, src/contacts/ViewContact/ContactEmails/ContactEmails.js, src/contacts/ViewContact/ContactPhoneNumbers/ContactPhoneNumbers.js, src/contacts/ViewContact/ContactUrls/ContactUrls.js
From the comment we discovered that we need a similar fix to display labels for the selected language
https://issues.folio.org/browse/UIORGS-155
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
=> UIORGS-155 display language labels

CHANGELOG.md, src/Organizations/OrganizationDetails/OrganizationDetails.js
Delete action at top of action menu
https://issues.folio.org/browse/UIORGS-154
While it's …
=> UIORGS-154 Delete action at top of action menu

CHANGELOG.md, src/Organizations/OrganizationForm/OrganizationContactPeopleForm/OrganizationContactPeopleList.js, src/Organizations/OrganizationForm/OrganizationInterfacesForm/OrganizationInterfacesList.js
https://issues.folio.org/browse/UINV-138 …
=> UINV-138 align delete button to the end

CHANGELOG.md, src/Organizations/OrganizationDetails/OrganizationContactPeople/OrganizationContactPeople.js, src/Organizations/OrganizationDetails/OrganizationContactPeople/OrganizationContactPeopleContainer.js, src/Organizations/OrganizationDetails/OrganizationInterfaces/OrganizationInterfacesContainer.js, src/Organizations/OrganizationForm/OrganizationContactPeopleForm/OrganizationContactPeopleForm.js, src/Organizations/OrganizationForm/OrganizationForm.js, src/Organizations/OrganizationForm/OrganizationInterfacesForm/OrganizationInterfacesForm.js, src/Organizations/OrganizationForm/OrganizationInterfacesForm/OrganizationInterfacesList.js, test/bigtest/interactors/organizationEdit.js, test/bigtest/tests/organizationEdit.e2e.js
https://issues.folio.org/browse/UIORGS-128 …
=> UIORGS-128 Edit Organizations: Interface table does not look right

CHANGELOG.md, src/Organizations/OrganizationsList/OrganizationsList.js, src/Organizations/OrganizationsList/OrganizationsListContainer.js
Organizations is not using the same Expand/Collapse as implemented in Q4 2019
https://issues.folio.org/browse/UIORGS-151 …
=> UIORGS-151 use common collapse/expnd filters icons

src/Organizations/OrganizationsList/OrganizationsList.js, src/Organizations/OrganizationsList/OrganizationsListContainer.js
use common comp for no results message, fix fetching data if no filters selected(only sorting)
https://issues.folio.org/browse/UIORGS-151 …
=> UIORGS-115 use common component

CHANGELOG.md, package.json, src/Organizations/OrganizationCreate/OrganizationCreate.js, src/Organizations/OrganizationEdit/OrganizationEdit.js, src/common/components/AddressInfo/AddressInfo.js, src/common/components/FieldLanguage/FieldLanguage.js
https://issues.folio.org/browse/UIORGS-180 …
=> UIORGS-180 Update to Stripes v4

CHANGELOG.md, package.json, src/common/constants/api.js, src/common/resources/organization.js, test/bigtest/network/configs/organizations.js, test/bigtest/tests/OrganizationDetails/OrganizationDetailsNoEdit.e2e.js
https://issues.folio.org/browse/UIORGS-178 …
=> UIORGS-178 Switch to mod-organizations

CHANGELOG.md, index.js, src/Organizations/OrganizationForm/OrganizationSummaryForm/OrganizationSummaryForm.js, src/Organizations/OrganizationsList/OrganizationsListFilter/OrganizationsListFilter.js, src/Organizations/OrganizationsList/OrganizationsListFilter/constants.js, src/contacts/ContactsContainer.js, src/contacts/ViewContact/ViewContactContainer.js, src/interfaces/EditInterface/EditInterfaceContainer.js, src/interfaces/InterfaceContainer.js, src/interfaces/ViewInterface/ViewInterfaceContainer.js, test/bigtest/tests/noPermissions/noDeletePermission.e2e.js, test/bigtest/tests/noPermissions/noEditPermission.e2e.js, test/bigtest/tests/organizationsList.e2e.js, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-176 …
=> UIORGS-176 acq unit filter

translations/ui-organizations/ar.json, translations/ui-organizations/ca.json, translations/ui-organizations/da.json, translations/ui-organizations/de.json, translations/ui-organizations/en_GB.json, translations/ui-organizations/en_SE.json, translations/ui-organizations/en_US.json, translations/ui-organizations/es.json, translations/ui-organizations/es_419.json, translations/ui-organizations/es_ES.json, translations/ui-organizations/fr.json, translations/ui-organizations/fr_FR.json, translations/ui-organizations/he.json, translations/ui-organizations/hu.json, translations/ui-organizations/it_IT.json, translations/ui-organizations/ja.json, translations/ui-organizations/pt_BR.json, translations/ui-organizations/pt_PT.json, translations/ui-organizations/ru.json, translations/ui-organizations/ur.json, translations/ui-organizations/zh_CN.json, translations/ui-organizations/zh_TW.json
=> Update translation strings as of 20200522T132417

translations/ui-organizations/fr_FR.json, translations/ui-organizations/pt_BR.json
=> Update translation strings as of 20200526T141248

CHANGELOG.md, package.json, src/Organizations/OrganizationDetails/OrganizationDetails.js, src/Organizations/OrganizationDetails/OrganizationSummary/OrganizationSummary.js, src/Organizations/OrganizationForm/OrganizationSummaryForm/OrganizationSummaryForm.js, src/Organizations/constants.js, test/bigtest/interactors/organizationsList.js, translations/ui-organizations/en.json
Ability to assign acquisition unit(s) to organization records
https://issues.folio.org/browse/UIORGS-121
Could be merged after [MODORG-3](https://issues.folio.org/browse/MODORG-3) is ready
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …
=> UIORGS-121 Ability to assign acquisition unit(s) to organization records

CHANGELOG.md, src/common/components/ButtonIsPrimary/ButtonIsPrimary.js, src/contacts/EditContact/EmailForm/EmailForm.js, src/contacts/EditContact/PhoneForm/PhoneForm.js, src/contacts/EditContact/UrlForm/UrlForm.js
Contact people create and Edit form object overlap
https://issues.folio.org/browse/UIORGS-135 …
=> UIORGS-135 fix overlap isPrimary and Delete btn

CHANGELOG.md, src/Organizations/OrganizationForm/OrganizationSummaryForm/OrganizationSummaryForm.js, src/Organizations/OrganizationForm/asyncValidate.js, src/Organizations/handleSaveErrorResponse.js, test/bigtest/tests/organizationCreate.e2e.js, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-177 …
=> UIORGS-177 space in the Code returns an incorrect error

src/contacts/EditContact/EmailForm/EmailForm.js, src/contacts/EditContact/UrlForm/UrlForm.js
https://issues.folio.org/browse/UIORGS-135 …
=> UIORGS-135 revise the fix

src/Organizations/OrganizationCreate/OrganizationCreate.js, src/Organizations/OrganizationDetails/OrganizationDetailsContainer.js, src/Organizations/OrganizationEdit/OrganizationEdit.js
=> UIOR-567 fix missing callouts

translations/ui-organizations/ar.json, translations/ui-organizations/ca.json, translations/ui-organizations/da.json, translations/ui-organizations/de.json, translations/ui-organizations/en_GB.json, translations/ui-organizations/en_SE.json, translations/ui-organizations/en_US.json, translations/ui-organizations/es.json, translations/ui-organizations/es_419.json, translations/ui-organizations/es_ES.json, translations/ui-organizations/fr.json, translations/ui-organizations/fr_FR.json, translations/ui-organizations/he.json, translations/ui-organizations/hu.json, translations/ui-organizations/it_IT.json, translations/ui-organizations/ja.json, translations/ui-organizations/pt_BR.json, translations/ui-organizations/pt_PT.json, translations/ui-organizations/ru.json, translations/ui-organizations/ur.json, translations/ui-organizations/zh_CN.json, translations/ui-organizations/zh_TW.json
=> Update translation strings as of 20200604T202430

translations/ui-organizations/fr_FR.json, translations/ui-organizations/zh_CN.json
=> Update translation strings as of 20200615T161518

CHANGELOG.md, src/Organizations/OrganizationsList/OrganizationsList.js, src/Organizations/OrganizationsList/OrganizationsListFilter/OrganizationsListFilter.js
https://issues.folio.org/browse/UIORGS-157 …
=> UIORGS-157 Accessibility error: IDs must be unique

CHANGELOG.md, src/Organizations/OrganizationDetails/OrganizationEDIInfo/OrganizationEDIInfo.js, src/Organizations/OrganizationDetails/OrganizationInterfaces/OrganizationInterface/OrganizationInterface.js, src/Organizations/OrganizationDetails/OrganizationSummary/OrganizationSummary.js, src/Organizations/OrganizationDetails/OrganizationVendorInfo/OrganizationVendorInfo.js
https://issues.folio.org/browse/UIORGS-159 …
=> UIORGS-159 Accessibility Error: Form elements must have labels

CHANGELOG.md, src/Organizations/OrganizationDetails/OrganizationSummary/OrganizationSummary.js
Alias descriptions not displayed if Alias 1 has no description
https://issues.folio.org/browse/UIORGS-189 …
=> UIORGS-189 fix Aliases MCL

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIORGS-188 …
=> UIORGS-188 backport release to master

translations/ui-organizations/ar.json, translations/ui-organizations/ca.json, translations/ui-organizations/da.json, translations/ui-organizations/de.json, translations/ui-organizations/en_GB.json, translations/ui-organizations/en_SE.json, translations/ui-organizations/en_US.json, translations/ui-organizations/es.json, translations/ui-organizations/es_419.json, translations/ui-organizations/es_ES.json, translations/ui-organizations/fr.json, translations/ui-organizations/fr_FR.json, translations/ui-organizations/he.json, translations/ui-organizations/hu.json, translations/ui-organizations/it_IT.json, translations/ui-organizations/ja.json, translations/ui-organizations/pt_BR.json, translations/ui-organizations/pt_PT.json, translations/ui-organizations/ru.json, translations/ui-organizations/ur.json, translations/ui-organizations/zh_CN.json, translations/ui-organizations/zh_TW.json
=> Update translation strings as of 20200701T150841

CHANGELOG.md, src/Utils/TogglePassword.js
https://issues.folio.org/browse/UIORGS-172 …
=> UIORGS-172 Form elements must have labels

CHANGELOG.md, package.json, src/Organizations/OrganizationForm/OrganizationVendorInfoForm/OrganizationVendorInfoForm.js
ACQ - CurrencySelect values are not translated
https://issues.folio.org/browse/UISACQCOMP-2 …
=> UISACQCOMP-2 CurrencySelect values are not translated

CHANGELOG.md, src/Organizations/OrganizationForm/OrganizationContactPeopleForm/OrganizationContactPeopleList.js, src/Organizations/OrganizationForm/OrganizationInterfacesForm/OrganizationInterfacesList.js
https://issues.folio.org/browse/UIORGS-162 …
=> UIORGS-162 Accessibility Error: Buttons must have discernible text

CHANGELOG.md, src/ContactPeople/ContactPerson/ContactPersonAddresses/ContactPersonAddress.js, src/contacts/ViewContact/ContactAddresses/ContactAddress.js
https://issues.folio.org/browse/UIORGS-166 …
=> UIORGS-166 Heading levels should only increase by one

CHANGELOG.md, src/Organizations/OrganizationForm/OrganizationContactPeopleForm/OrganizationContactPeopleList.js, src/Organizations/OrganizationForm/OrganizationInterfacesForm/OrganizationInterfacesList.js, src/Organizations/OrganizationForm/OrganizationInterfacesForm/constants.js, src/contacts/ViewContact/ContactEmails/ContactEmails.js, src/contacts/ViewContact/ContactPhoneNumbers/ContactPhoneNumbers.js, src/contacts/ViewContact/ContactUrls/ContactUrls.js, src/contacts/constants.js
https://issues.folio.org/browse/UIORGS-169 …
=> UIORGS-169 Accessibility Error: id attribute value must be unique

CHANGELOG.md, src/Organizations/OrganizationForm/OrganizationContactInfoForm/ContactInfoFormGroup/EmailAddresses.js, src/Organizations/OrganizationForm/OrganizationContactInfoForm/ContactInfoFormGroup/PhoneNumbers.js, src/Organizations/OrganizationForm/OrganizationContactInfoForm/ContactInfoFormGroup/Urls.js, src/Organizations/OrganizationForm/OrganizationVendorInfoForm/OrganizationVendorInfoForm.js, src/Utils/CategoryDropdown.js, src/common/components/AddressInfo/AddressInfo.js, src/contacts/EditContact/EditContact.js, src/contacts/EditContact/PhoneForm/PhoneForm.js
https://issues.folio.org/browse/UIORGS-170 …
=> UIORGS-170 Form elements must have labels

translations/ui-organizations/zh_CN.json
=> Update translation strings as of 20200721T202356

translations/ui-organizations/ru.json
=> Update translation strings as of 20200723T131158

src/Organizations/OrganizationForm/OrganizationSummaryForm/OrganizationSummaryForm.js, src/Organizations/OrganizationsList/OrganizationsList.js, src/Organizations/OrganizationsList/OrganizationsListContainer.js, src/Organizations/OrganizationsList/OrganizationsListFilter/OrganizationsListFilter.js, src/Organizations/OrganizationsList/OrganizationsListLastMenu.js, src/Organizations/OrganizationsList/OrganizationsListSearchConfig.js, src/contacts/EditContact/EmailForm/EmailForm.js, src/contacts/EditContact/UrlForm/UrlForm.js
Update subheading of the Organizations landing page Search results pane
https://issues.folio.org/browse/UIORGS-191 …
=> UIORGS-191 Update subheading of the Organizations results pane

CHANGELOG.md, src/Organizations/OrganizationForm/OrganizationAccountsForm/OrganizationAccountsForm.js, test/bigtest/interactors/orgSections/AccountsSection.js, test/bigtest/network/factories/organization.js, test/bigtest/tests/vendorEdit.e2e.js
Fix Can not add add accounts to organization from edit form
https://issues.folio.org/browse/UIORGS-193 …
=> UIORGS-193

CHANGELOG.md, package.json
=> backport-v2.1.2-release

CHANGELOG.md, src/Organizations/OrganizationDetails/OrganizationContactPeople/OrganizationContactPeopleContainer.js, src/Organizations/OrganizationForm/OrganizationContactPeopleForm/OrganizationContactPeopleList.js
https://issues.folio.org/browse/UIORGS-192 …
=> UIORGS-192 Display contacts in alphabetical order

src/Organizations/OrganizationDetails/OrganizationContactPeople/OrganizationContactPeople.js, src/Organizations/OrganizationDetails/OrganizationContactPeople/OrganizationContactPeopleContainer.js, src/Organizations/OrganizationForm/OrganizationContactPeopleForm/OrganizationContactPeopleList.js
https://issues.folio.org/browse/UIORGS-192?focusedCommentId=84479&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-84479 …
=> UIORGS-192 Display contacts

CHANGELOG.md, src/Organizations/OrganizationDetails/OrganizationDetailsContainer.js, src/Organizations/OrganizationsList/OrganizationsList.js, src/Organizations/OrganizationsList/OrganizationsListContainer.js, src/Organizations/OrganizationsList/OrganizationsListFilter/OrganizationsListFilterConfig.js, src/common/resources/organization.js
https://issues.folio.org/browse/UIORGS-197 …
=> UIORGS-197 fix sorting and loading list

CHANGELOG.md, src/Organizations/OrganizationDetails/OrganizationDetails.js, src/Organizations/OrganizationDetails/OrganizationVendorInfo/OrganizationVendorInfo.js, src/Organizations/OrganizationForm/OrganizationVendorInfoForm/OrganizationVendorInfoForm.js, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-186 …
=> UIORGS-186 Add "Export to accounting" toggle

translations/ui-organizations/ar.json, translations/ui-organizations/ca.json, translations/ui-organizations/da.json, translations/ui-organizations/de.json, translations/ui-organizations/en_GB.json, translations/ui-organizations/en_SE.json, translations/ui-organizations/en_US.json, translations/ui-organizations/es.json, translations/ui-organizations/es_419.json, translations/ui-organizations/es_ES.json, translations/ui-organizations/fr.json, translations/ui-organizations/fr_FR.json, translations/ui-organizations/he.json, translations/ui-organizations/hu.json, translations/ui-organizations/it_IT.json, translations/ui-organizations/ja.json, translations/ui-organizations/pt_BR.json, translations/ui-organizations/pt_PT.json, translations/ui-organizations/ru.json, translations/ui-organizations/ur.json, translations/ui-organizations/zh_CN.json, translations/ui-organizations/zh_TW.json
=> Update translation strings as of 20200827T215834

src/Organizations/OrganizationDetails/OrganizationDetails.js
https://issues.folio.org/browse/UIORGS-184 …
=> UIORGS-184 move accordion up

CHANGELOG.md, src/Organizations/OrganizationForm/OrganizationSummaryForm/OrganizationSummaryForm.js
https://issues.folio.org/browse/UIORGS-190 …
=> UIORGS-190 Allow use of spaces in organization code

translations/ui-organizations/ar.json, translations/ui-organizations/ca.json, translations/ui-organizations/da.json, translations/ui-organizations/de.json, translations/ui-organizations/en_GB.json, translations/ui-organizations/en_SE.json, translations/ui-organizations/en_US.json, translations/ui-organizations/es.json, translations/ui-organizations/es_419.json, translations/ui-organizations/es_ES.json, translations/ui-organizations/fr.json, translations/ui-organizations/fr_FR.json, translations/ui-organizations/he.json, translations/ui-organizations/hu.json, translations/ui-organizations/it_IT.json, translations/ui-organizations/ja.json, translations/ui-organizations/pt_BR.json, translations/ui-organizations/pt_PT.json, translations/ui-organizations/ru.json, translations/ui-organizations/ur.json, translations/ui-organizations/zh_CN.json, translations/ui-organizations/zh_TW.json
=> Update translation strings as of 20200901T173106

CHANGELOG.md, package.json, src/Utils/TogglePassword.js, src/interfaces/EditInterface/EditInterface.js, src/interfaces/EditInterface/const.js
fix Can NOT remove delivery method from interface
https://issues.folio.org/browse/UIORGS-199 …
=> UIORGS-199 switch interface form to RFF

CHANGELOG.md, src/Organizations/OrganizationForm/OrganizationEDIInfoForm/OrganizationEDIInfoForm.js, src/Utils/CategoryDropdown.js
https://issues.folio.org/browse/UIORGS-198 …
=> UIORGS-198 fix filtering in categories

.gitignore, CHANGELOG.md, Jenkinsfile, jest.config.js, package.json, src/Organizations/OrganizationDetails/OrganizationAccounts/OrganizationAccount/OrganizationAccount.js, src/Organizations/OrganizationDetails/OrganizationAgreements/OrganizationAgreement.js, src/Organizations/OrganizationDetails/OrganizationAgreements/OrganizationAgreements.js, src/Organizations/OrganizationDetails/OrganizationContactPeople/OrganizationContactPeople.js, src/Organizations/OrganizationDetails/OrganizationEDIInfo/OrganizationEDIInfo.js, src/Organizations/OrganizationDetails/OrganizationInterfaces/OrganizationInterface/OrganizationInterface.css, src/Organizations/OrganizationDetails/OrganizationInterfaces/OrganizationInterface/OrganizationInterface.js, src/Organizations/OrganizationDetails/OrganizationSummary/OrganizationSummary.js, src/Organizations/OrganizationDetails/OrganizationSummary/OrganizationSummary.test.js, src/Organizations/OrganizationDetails/OrganizationVendorInfo/OrganizationVendorInfo.js, src/Organizations/OrganizationForm/OrganizationAccountsForm/OrganizationAccountsForm.css, src/common/styles/subHeadings.css, src/interfaces/EditInterface/EditInterface.css, src/interfaces/EditInterface/EditInterface.js, test/bigtest/tests/organizationCreate.e2e.js
* also added jest+rtl unit tests
https://issues.folio.org/browse/UIORGS-201
While it's …
=> UIORGS-201 Update view pane to display null as hyphen

CHANGELOG.md, src/Organizations/OrganizationCreate/OrganizationCreate.js, src/Organizations/OrganizationForm/OrganizationEDIInfoForm/OrganizationEDIInfoForm.js
https://issues.folio.org/browse/UIORGS-203 …
=> UIORGS-203 Select list default values not saving

src/Organizations/OrganizationDetails/OrganizationEDIInfo/OrganizationEDIInfo.js, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-203?focusedCommentId=87653&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-87653 …
=> UIORGS-203 Add FTP connection mode

translations/ui-organizations/ar.json, translations/ui-organizations/ca.json, translations/ui-organizations/da.json, translations/ui-organizations/de.json, translations/ui-organizations/en_GB.json, translations/ui-organizations/en_SE.json, translations/ui-organizations/en_US.json, translations/ui-organizations/es.json, translations/ui-organizations/es_419.json, translations/ui-organizations/es_ES.json, translations/ui-organizations/fr.json, translations/ui-organizations/fr_FR.json, translations/ui-organizations/he.json, translations/ui-organizations/hi_IN.json, translations/ui-organizations/hu.json, translations/ui-organizations/it_IT.json, translations/ui-organizations/ja.json, translations/ui-organizations/ko.json, translations/ui-organizations/pl.json, translations/ui-organizations/pt_BR.json, translations/ui-organizations/pt_PT.json, translations/ui-organizations/ru.json, translations/ui-organizations/ur.json, translations/ui-organizations/zh_CN.json, translations/ui-organizations/zh_TW.json
=> Update translation strings as of 20200928T202231

CHANGELOG.md, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-205 …
=> UIORGS-205 Add "add alternative names" button label

CHANGELOG.md, src/Organizations/OrganizationCreate/OrganizationCreate.js, src/Organizations/OrganizationDetails/OrganizationDetails.js, src/Organizations/OrganizationEdit/OrganizationEdit.js, src/Organizations/OrganizationsList/OrganizationsList.js
https://issues.folio.org/browse/UIORGS-206 …
=> UIORGS-206 Focus details pane after user redirected

CHANGELOG.md, src/Organizations/OrganizationsList/OrganizationsList.js
Focus details pane after user clicks on org in the search results
https://issues.folio.org/browse/UIORGS-207 …
=> UIORGS-207 focus after clicking on an org

CHANGELOG.md, src/contacts/EditContact/EmailForm/EmailForm.js, src/contacts/EditContact/PhoneForm/PhoneForm.js, src/contacts/EditContact/UrlForm/UrlForm.js
https://issues.folio.org/browse/UIORGS-210
https://github.com/folio-org/stripes-components/pull/1418 …
=> UIORGS-210 Accessibility Error: Buttons must have discernible text

CHANGELOG.md, src/Organizations/OrganizationsList/OrganizationsList.js, src/Organizations/OrganizationsList/OrganizationsListContainer.js
Org list - Move focus to results pane when response has come
https://issues.folio.org/browse/UIORGS-208 …
=> UIORGS-208 focus results list

CHANGELOG.md, package.json, src/Organizations/OrganizationDetails/OrganizationDetailsContainer.js, src/Organizations/OrganizationDetails/OrganizationEDIInfo/OrganizationEDIInfo.js
https://issues.folio.org/browse/UIORGS-211 …
=> UIORGS-211 backport of release

CHANGELOG.md, PERSONAL_DATA_DISCLOSURE.md
https://issues.folio.org/browse/UIORGS-222 …
=> UIORGS-222 - Add personal data disclosure form

CHANGELOG.md, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-215 …
=> UIORGS-215 remove unused transl keys

.eslintrc, src/Organizations/OrganizationsList/OrganizationsListFilter/OrganizationsListFilterConfig.js, test/bigtest/.eslintrc
fix filtering of array fields, corresponding PR in SAC https://github.com/folio-org/stripes-acq-components/pull/414
initial PR introduced https://github.com/folio-org/stripes-acq-components/pull/394
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
=> fix filtering by array fields

package.json
https://issues.folio.org/browse/UIORGS-226 …
=> UIORGS-226 Update stripes-cli to v2

CHANGELOG.md, src/Organizations/OrganizationForm/OrganizationContactInfoForm/ContactInfoFormGroup/EmailAddresses.js
https://issues.folio.org/browse/UIORGS-217 …
=> UIORGS-217

CHANGELOG.md, src/Organizations/OrganizationForm/OrganizationEDIInfoForm/OrganizationEDIInfoForm.js, src/Organizations/OrganizationForm/OrganizationVendorInfoForm/OrganizationVendorInfoForm.js
https://issues.folio.org/browse/UIORGS-216
https://issues.folio.org/browse/UIORGS-218
While …
=> UIORGS-216, UIORGS-218 Translate accordions labels

CHANGELOG.md, src/common/components/AddressInfo/AddressInfo.js, src/common/components/FieldLanguage/FieldLanguage.js
Centralizing country and language data in stripes components
https://issues.folio.org/browse/UIORGS-227 …
=> UIORGS-227 use countries and languages from stripes-components

CHANGELOG.md, package.json, test/bigtest/tests/organizationsList.e2e.js, test/bigtest/tests/vendorOrganizationDetails.e2e.js
https://issues.folio.org/browse/UIORGS-221 …
=> Release v2.3.0

CHANGELOG.md, src/contacts/EditContact/EditContact.js, src/contacts/ViewContact/ViewContact.js
https://issues.folio.org/browse/UIORGS-231
use`AccordionStatus` …
=> UIORGS-231-Collapse all accordions(contact person)

CHANGELOG.md, package.json, src/common/components/AddressInfo/AddressInfo.js, src/common/utils/index.js, src/common/utils/removeItem.js, src/common/utils/removeItem.test.js, src/common/validation/index.js, src/common/validation/validatePrimary.js, src/common/validation/validatePrimary.test.js, src/contacts/EditContact/EmailForm/EmailForm.js, src/contacts/EditContact/PhoneForm/PhoneForm.js, src/contacts/EditContact/UrlForm/UrlForm.js, test/bigtest/network/factories/contact.js, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-232 …
=> UIORGS-232 Contact persons email does not appear in the view

CHANGELOG.md, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-233 …
=> UIORGS-233 State-Region label runs off the chart

CHANGELOG.md, src/Organizations/OrganizationDetails/OrganizationContactPeople/OrganizationContactPeople.js, src/Organizations/OrganizationDetails/OrganizationContactPeople/OrganizationContactPeopleContainer.js, src/Organizations/OrganizationForm/OrganizationContactPeopleForm/OrganizationContactPeopleList.js, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-234 …
=> UIORGS-234 Deleting a contact person assigned to multiple orgs creates UI error

CHANGELOG.md, src/Organizations/OrganizationEdit/OrganizationEdit.js
https://issues.folio.org/browse/UIORGS-236 …
=> UIORGS-236 EDI scheduling time incorrectly formatted on edit form

src/Organizations/OrganizationDetails/OrganizationDetailsContainer.js, src/Organizations/OrganizationsList/OrganizationsList.js
https://issues.folio.org/browse/UIORGS-239 …
=> UIORGS-239 Resizable Panes - Persistence

src/contacts/ViewContact/ViewContact.js
https://issues.folio.org/browse/UIORGS-242 …
=> UIORGS-242 remove copy for contact

src/interfaces/ViewInterface/ViewInterface.js
https://issues.folio.org/browse/UIORGS-241 …
=> UIORGS-241 remove copy interface btn

CHANGELOG.md, package.json, src/Organizations/OrganizationDetails/OrganizationDetails.js, test/bigtest/interactors/const.js, test/bigtest/tests/vendorEdit.e2e.js
https://issues.folio.org/browse/UIORGS-243 …
=> UIORGS-243 Organization - Acquisition units no longer restrict edit or delete actions from action menu

src/Organizations/OrganizationDetails/OrganizationDetails.js, src/Organizations/OrganizationForm/OrganizationForm.js, src/Organizations/Organizations.js, src/Organizations/OrganizationsList/OrganizationsList.js, src/contacts/ContactsContainer.js, src/contacts/EditContact/EditContact.js, src/contacts/ViewContact/ViewContact.js, src/interfaces/EditInterface/EditInterface.js, src/interfaces/InterfaceContainer.js, src/interfaces/ViewInterface/ViewInterface.js
https://issues.folio.org/browse/UIORGS-230 …
=> UIORGS-230 Apply basic shortcut keys

src/Organizations/OrganizationDetails/OrganizationDetails.js
https://issues.folio.org/browse/UIORGS-230 …
=> UIORGS-230 Missed acq unit restrictions

CHANGELOG.md, src/Organizations/OrganizationDetails/OrganizationContactPeople/OrganizationContactPeople.js
https://issues.folio.org/browse/UIORGS-248 …
=> UIORGS-248 Display contact people status in organization view

CHANGELOG.md, src/Organizations/OrganizationForm/OrganizationForm.js, src/Organizations/constants.js
https://issues.folio.org/browse/UIORGS-244
Check form.getState().errors for not filled required fields and force open accordions 
Remove AccordionStatus to control Accordions …
=> UIORGS-244 Force open accordion for required not filled fields

src/Organizations/OrganizationDetails/OrganizationDetails.js, src/Organizations/OrganizationForm/OrganizationForm.js, src/Organizations/Organizations.js, src/Organizations/OrganizationsList/OrganizationsList.js, src/contacts/EditContact/EditContact.js, src/contacts/ViewContact/ViewContact.js, src/interfaces/EditInterface/EditInterface.js, src/interfaces/ViewInterface/ViewInterface.js
=> use common handleKeyCommand

CHANGELOG.md, Jenkinsfile, package.json
https://issues.folio.org/browse/UIORGS-238 …
=> UIORGS-238 Compile Translation Files into AST

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIORGS-249 …
=> UIORGS-249 update package.json

package.json
=> FAT-40 change test scripts

CHANGELOG.md, src/Organizations/OrganizationForm/OrganizationSummaryForm/FieldCode/validateOrgCode.js, src/Organizations/OrganizationForm/OrganizationSummaryForm/FieldCode/validateOrgCode.test.js
https://issues.folio.org/browse/UIORGS-252 …
=> UIORGS-252 Wrap Organization code in double quotes when validating

src/contacts/ViewContact/ViewContact.js, src/interfaces/ViewInterface/ViewInterface.js
https://issues.folio.org/browse/UIORGS-251 …
=> UIORGS-251 show/hide contact/interface actions based on permissions

CHANGELOG.md, src/Organizations/OrganizationDetails/OrganizationContactInfo/OrganizationContactInfo.js, src/Organizations/OrganizationDetails/OrganizationSummary/OrganizationSummary.js
https://issues.folio.org/browse/UIORGS-255 …
=> UIORGS-255 Expand sub accordions when user clicks 'Expand all'

CHANGELOG.md, package.json, test/bigtest/tests/noPermissions/noDeletePermission.e2e.js, test/bigtest/tests/noPermissions/noEditPermission.e2e.js, test/bigtest/tests/noPermissions/noSettingsPermission.e2e.js, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-179 …
=> UIORGS-179 Add translations for permissions

CHANGELOG.md, package.json, src/Organizations/OrganizationsList/OrganizationsList.js, src/Organizations/OrganizationsList/OrganizationsList.test.js, src/Organizations/OrganizationsList/OrganizationsListContainer.js, src/Organizations/OrganizationsList/OrganizationsListContainer.test.js, src/Organizations/OrganizationsList/hooks/index.js, src/Organizations/OrganizationsList/hooks/useBuildQuery/index.js, src/Organizations/OrganizationsList/hooks/useBuildQuery/useBuildQuery.js, src/Organizations/OrganizationsList/hooks/useBuildQuery/useBuildQuery.test.js, src/Organizations/OrganizationsList/hooks/useOrganizations/index.js, src/Organizations/OrganizationsList/hooks/useOrganizations/useOrganizations.js, src/Organizations/OrganizationsList/hooks/useOrganizations/useOrganizations.test.js, src/common/resources/organization.js
https://issues.folio.org/browse/UIORGS-257 …
=> UIORGS-257 Organizations - Implement MCL Next/Previous pagination

src/Organizations/OrganizationsList/OrganizationsList.js, src/Organizations/OrganizationsList/OrganizationsListContainer.js, src/common/resources/organization.js
https://issues.folio.org/browse/UIORGS-257 …
=> UIORGS-257 Set the limit of organizations to 50 per request

CHANGELOG.md, src/Organizations/OrganizationForm/OrganizationAccountsForm/__snapshots__/OrganizationAccountsForm.test.js.snap, src/Organizations/OrganizationForm/OrganizationAgreementsForm/__snapshots__/OrganizationAgreementsForm.test.js.snap, src/Organizations/OrganizationForm/OrganizationSummaryForm/__snapshots__/OrganizationSummaryForm.test.js.snap, src/Organizations/OrganizationForm/OrganizationVendorInfoForm/__snapshots__/OrganizationVendorInfoForm.test.js.snap, src/Organizations/OrganizationForm/__snapshots__/OrganizationForm.test.js.snap, src/Organizations/OrganizationsList/OrganizationsListFilter/OrganizationsListFilter.js, src/Organizations/OrganizationsList/OrganizationsListFilter/__snapshots__/OrganizationsListFilter.test.js.snap, src/contacts/EditContact/__snapshots__/EditContact.test.js.snap, src/contacts/ViewContact/__snapshots__/ViewContact.test.js.snap, src/interfaces/EditInterface/__snapshots__/EditInterface.test.js.snap, test/bigtest/interactors/orgSections/SummarySection.js, test/bigtest/interactors/organizationEdit.js, test/bigtest/network/factories/category.js, test/bigtest/network/factories/contact.js, test/bigtest/network/factories/interface.js, test/bigtest/network/factories/organization.js, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-263 …
=> UIORGS-263 Filter label contains extra 's'

src/Organizations/OrganizationForm/OrganizationContactInfoForm/OrganizationContactInfoForm.test.js, src/Organizations/OrganizationForm/OrganizationContactInfoForm/__snapshots__/OrganizationContactInfoForm.test.js.snap, src/contacts/EditContact/EditContact.test.js, src/contacts/EditContact/__snapshots__/EditContact.test.js.snap
=> Release v3.0.1

src/Organizations/OrganizationDetails/OrganizationDetails.js, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-271 …
=> UIORG-271 Create integration action

src/OrganizationIntegration/OrganizationIntegrationForm/OrganizationIntegrationForm.js, src/OrganizationIntegration/OrganizationIntegrationForm/SchedulingForm/SchedulingForm.js, src/Organizations/constants.js
https://issues.folio.org/browse/UIORGS-271 …
=> UIORGS-271 integration configs: remove duplciation

src/OrganizationIntegration/OrganizationIntegrationForm/SchedulingForm/SchedulingForm.js
https://issues.folio.org/browse/UIORGS-271 …
=> UIORGS-271 parse time in (HH:mm:ss) format

CHANGELOG.md, src/OrganizationIntegration/OrganizationIntegrationCreate/OrganizationIntegrationCreate.js
https://issues.folio.org/browse/UIORGS-280 …
=> UIORGS-280 UI EDI migration process

src/OrganizationIntegration/OrganizationIntegrationCreate/OrganizationIntegrationCreate.js
=> UIORGS-271 fix edi migration for orgs without edi

CHANGELOG.md, src/OrganizationIntegration/OrganizationIntegrationForm/__snapshots__/OrganizationIntegrationForm.test.js.snap, src/OrganizationIntegration/OrganizationIntegrationView/__snapshots__/OrganizationIntegrationView.test.js.snap, src/Organizations/OrganizationDetails/OrganizationDetails.js, src/Organizations/OrganizationDetails/OrganizationDetails.test.js, src/Organizations/OrganizationForm/OrganizationAccountsForm/FieldAccountNumber/FieldAccountNumber.js, src/Organizations/OrganizationForm/OrganizationAccountsForm/FieldAccountNumber/FieldAccountNumber.test.js, src/Organizations/OrganizationForm/OrganizationAccountsForm/FieldAccountNumber/index.js, src/Organizations/OrganizationForm/OrganizationAccountsForm/OrganizationAccountsForm.js, src/Organizations/OrganizationForm/OrganizationContactPeopleForm/__snapshots__/OrganizationContactPeopleForm.test.js.snap, src/Organizations/OrganizationForm/OrganizationInterfacesForm/__snapshots__/OrganizationInterfacesForm.test.js.snap, src/Organizations/OrganizationForm/OrganizationVendorInfoForm/__snapshots__/OrganizationVendorInfoForm.test.js.snap, src/Organizations/OrganizationForm/__snapshots__/OrganizationForm.test.js.snap, src/Organizations/OrganizationsList/OrganizationsListFilter/__snapshots__/OrganizationsListFilter.test.js.snap, src/contacts/EditContact/__snapshots__/EditContact.test.js.snap, src/contacts/ViewContact/__snapshots__/ViewContact.test.js.snap, src/interfaces/EditInterface/__snapshots__/EditInterface.test.js.snap, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-292 …
=> UIORGS-292 Validation for "Account number" must be unique for organization

src/OrganizationIntegration/OrganizationIntegrationView/SchedulingView/SchedulingView.js
=> UIORGS-300 Fix deps

CHANGELOG.md, src/OrganizationIntegration/OrganizationIntegrationCreate/OrganizationIntegrationCreate.js, src/OrganizationIntegration/OrganizationIntegrationForm/EdiForm/EdiForm.js, src/OrganizationIntegration/OrganizationIntegrationForm/__snapshots__/OrganizationIntegrationForm.test.js.snap, src/OrganizationIntegration/constants.js, src/OrganizationIntegration/utils.js, src/OrganizationIntegration/utils.test.js, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-301 …
=> UIORGS-301 Allow user to set EDI naming convention

CHANGELOG.md, src/ContactPeople/ContactPerson/ContactPersonURLs/ContactPersonURLs.js, src/ContactPeople/ContactPerson/__snapshots__/ContactPerson.test.js.snap, src/Organizations/OrganizationDetails/OrganizationInterfaces/OrganizationInterface/OrganizationInterface.js, src/Organizations/OrganizationForm/OrganizationInterfacesForm/OrganizationInterfacesList.js, src/Organizations/OrganizationForm/OrganizationInterfacesForm/__snapshots__/OrganizationInterfacesForm.test.js.snap, src/contacts/ViewContact/ContactUrls/ContactUrls.js, src/contacts/ViewContact/__snapshots__/ViewContact.test.js.snap
https://issues.folio.org/browse/UIORGS-299 …
=> UIORGS-299 URLs should be hyperlinks in the view

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIORGS-265 …
=> UIORGS-265 refactor psets away from backend ".all" permissions

CHANGELOG.md, src/OrganizationIntegration/OrganizationIntegrationView/EdiView/EdiView.js, src/OrganizationIntegration/OrganizationIntegrationView/OrganizationIntegrationView.js, src/OrganizationIntegration/OrganizationIntegrationView/__snapshots__/OrganizationIntegrationView.test.js.snap, src/Organizations/OrganizationDetails/OrganizationDetails.js
https://issues.folio.org/browse/UINV-359 …
=> UINV-359 ui-organizations accessibility analysis

src/Organizations/OrganizationDetails/IntegrationDetails/IntegrationDetails.js
=> UIORGS-303 ui-organizations accessibility analysis

CHANGELOG.md, package.json, src/ContactPeople/ContactPerson/__snapshots__/ContactPerson.test.js.snap, src/OrganizationIntegration/OrganizationIntegrationForm/OrganizationIntegrationForm.js, src/OrganizationIntegration/OrganizationIntegrationForm/OrganizationIntegrationForm.test.js, src/OrganizationIntegration/OrganizationIntegrationForm/__snapshots__/OrganizationIntegrationForm.test.js.snap, src/OrganizationIntegration/OrganizationIntegrationView/OrganizationIntegrationView.js, src/OrganizationIntegration/OrganizationIntegrationView/OrganizationIntegrationView.test.js, src/OrganizationIntegration/OrganizationIntegrationView/__snapshots__/OrganizationIntegrationView.test.js.snap, src/Organizations/OrganizationDetails/OrganizationAccounts/OrganizationAccounts.test.js, src/Organizations/OrganizationDetails/OrganizationAccounts/__snapshots__/OrganizationAccounts.test.js.snap, src/Organizations/OrganizationForm/OrganizationForm.js, src/Organizations/OrganizationForm/OrganizationForm.test.js, src/Organizations/OrganizationForm/OrganizationVendorInfoForm/OrganizationVendorInfoForm.js, src/Organizations/OrganizationForm/OrganizationVendorInfoForm/OrganizationVendorInfoForm.test.js, src/Organizations/OrganizationForm/OrganizationVendorInfoForm/__snapshots__/OrganizationVendorInfoForm.test.js.snap, src/Organizations/OrganizationForm/__snapshots__/OrganizationForm.test.js.snap, src/Organizations/OrganizationsList/OrganizationsListFilter/OrganizationsListFilter.js, src/Organizations/OrganizationsList/OrganizationsListFilter/OrganizationsListFilter.test.js, src/Organizations/OrganizationsList/OrganizationsListFilter/__snapshots__/OrganizationsListFilter.test.js.snap, src/contacts/EditContact/EditContact.js, src/contacts/EditContact/EditContact.test.js, src/contacts/EditContact/__snapshots__/EditContact.test.js.snap, src/contacts/ViewContact/ViewContact.js, src/contacts/ViewContact/ViewContact.test.js, src/contacts/ViewContact/__snapshots__/ViewContact.test.js.snap, test/jest/fixtures/contact.js, test/jest/fixtures/integrationConfig.js
https://issues.folio.org/browse/UIORGS-302 …
=> Release v3.1.0

package.json
=> bump up stripes-acq-version

CHANGELOG.md, src/Organizations/OrganizationForm/OrganizationContactPeopleForm/__snapshots__/OrganizationContactPeopleForm.test.js.snap, src/Organizations/OrganizationForm/OrganizationInterfacesForm/__snapshots__/OrganizationInterfacesForm.test.js.snap, src/contacts/ViewContact/ViewContact.js, src/contacts/ViewContact/__snapshots__/ViewContact.test.js.snap
https://issues.folio.org/browse/UIORGS-305 …
=> UIORGS-305 Add record metadata widget to contact person

CHANGELOG.md, src/Organizations/OrganizationDetails/LinkedAgreements/LinkedAgreements.js, src/Organizations/OrganizationDetails/LinkedAgreements/LinkedAgreements.test.js, src/Organizations/OrganizationDetails/LinkedAgreements/constants.js, src/Organizations/OrganizationDetails/LinkedAgreements/index.js, src/Organizations/OrganizationDetails/OrganizationDetails.js, src/Organizations/OrganizationDetails/OrganizationDetails.test.js, src/Organizations/constants.js, src/common/constants/api.js, src/common/hooks/index.js, src/common/hooks/useLinkedAgreements/index.js, src/common/hooks/useLinkedAgreements/useLinkedAgreements.js, src/common/hooks/useLinkedAgreements/useLinkedAgreements.test.js, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-306 …
=> UIORGS-306 Display linked agreements on an organization record

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIORGS-307 …
=> UIORGS-307 Can not delete integration from organization

CHANGELOG.md, package.json, src/Organizations/OrganizationForm/OrganizationContactInfoForm/__snapshots__/OrganizationContactInfoForm.test.js.snap, src/Organizations/OrganizationForm/OrganizationSummaryForm/__snapshots__/OrganizationSummaryForm.test.js.snap, src/Organizations/OrganizationForm/__snapshots__/OrganizationForm.test.js.snap, src/Organizations/OrganizationsList/OrganizationsListFilter/__snapshots__/OrganizationsListFilter.test.js.snap, src/contacts/EditContact/__snapshots__/EditContact.test.js.snap
https://issues.folio.org/browse/UIORGS-308 …
=> UIORGS-308 Release v3.1.1

CHANGELOG.md, package.json, src/Organizations/constants.js
https://issues.folio.org/browse/UIORGS-312 …
=> UIORGS-312 Manage acquisition unit permission not working

CHANGELOG.md, index.js, package.json, src/OrganizationIntegration/utils.test.js
https://issues.folio.org/browse/UIORGS-313 …
=> UIORGS-313 Replace or remove react-hot-loader

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIORGS-314 …
=> UIORGS-314 release v3.1.2

.eslintrc, CHANGELOG.md, package.json, src/Organizations/OrganizationForm/OrganizationAccountsForm/__snapshots__/OrganizationAccountsForm.test.js.snap, src/Organizations/OrganizationForm/OrganizationContactInfoForm/__snapshots__/OrganizationContactInfoForm.test.js.snap, src/Organizations/OrganizationForm/OrganizationSummaryForm/__snapshots__/OrganizationSummaryForm.test.js.snap, src/Organizations/OrganizationForm/OrganizationVendorInfoForm/__snapshots__/OrganizationVendorInfoForm.test.js.snap, src/Organizations/OrganizationsList/OrganizationsListFilter/__snapshots__/OrganizationsListFilter.test.js.snap, src/contacts/EditContact/__snapshots__/EditContact.test.js.snap
https://issues.folio.org/browse/UIORGS-317 …
=> UIORGS-317 replace babel-eslint with @babel/eslint-parser

CHANGELOG.md, package.json, src/OrganizationIntegration/OrganizationIntegrationForm/FtpForm/FtpForm.js, src/OrganizationIntegration/OrganizationIntegrationForm/__snapshots__/OrganizationIntegrationForm.test.js.snap, src/OrganizationIntegration/OrganizationIntegrationView/FtpView/FtpView.js, src/OrganizationIntegration/OrganizationIntegrationView/__snapshots__/OrganizationIntegrationView.test.js.snap, src/common/components/Credentials/Credentials.css, src/common/components/Credentials/Credentials.js, src/common/components/Credentials/index.js, src/common/components/CredentialsField/CredentialsField.js, src/common/components/CredentialsField/CredentialsField.test.js, src/common/components/CredentialsField/index.js, src/common/components/index.js, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-316 …
=> UIORGS-316 Add specific permissions for Integration FTP username and password

CHANGELOG.md, src/OrganizationIntegration/OrganizationIntegrationForm/EdiForm/EdiForm.js, src/OrganizationIntegration/OrganizationIntegrationForm/FtpForm/FtpForm.js, src/OrganizationIntegration/OrganizationIntegrationForm/__snapshots__/OrganizationIntegrationForm.test.js.snap
https://issues.folio.org/browse/UIORGS-318 …
=> UIORGS-318 Make fields required

src/OrganizationIntegration/OrganizationIntegrationForm/FtpForm/FtpForm.js, src/OrganizationIntegration/OrganizationIntegrationForm/__snapshots__/OrganizationIntegrationForm.test.js.snap
https://issues.folio.org/browse/UIORGS-318?focusedCommentId=130018&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-130018 …
=> UIORGS-318 server address is required

Jenkinsfile
This is a temporary upgrade to verify Jenkins using Node 16.
=> FOLIO-3511 verify jenkins build with Node.js v16

CHANGELOG.md, src/Organizations/OrganizationForm/OrganizationSummaryForm/OrganizationSummaryForm.js, src/Organizations/OrganizationForm/OrganizationSummaryForm/resetVendorFields.js
https://issues.folio.org/browse/UIORGS-325 …
=> UIORGS-325 Edit Organizations record: Unselecting Vendor checkbox results in 400 error

CHANGELOG.md, src/OrganizationIntegration/OrganizationIntegrationForm/SchedulingForm/SchedulingForm.js, src/OrganizationIntegration/constants.js, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-330
Exclude hourly and monthly options on edit form - replaced by None
Revert this as soon as scheduler works fine for removed options …
=> UIORGS-330 disable hourly and monthly schedule periods

CHANGELOG.md, src/OrganizationIntegration/OrganizationIntegrationView/SchedulingView/SchedulingView.js, src/Organizations/OrganizationForm/OrganizationContactInfoForm/__snapshots__/OrganizationContactInfoForm.test.js.snap, src/Organizations/OrganizationForm/__snapshots__/OrganizationForm.test.js.snap
https://issues.folio.org/browse/UIORGS-331 …
=> UIORGS-331 The days previously selected for weekly scheduling are displayed in the updated scheduling settings

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIORGS-333
Remove unused dependency …
=> UIORGS-333 react-tether is incompatible with react 17

CHANGELOG.md, src/OrganizationIntegration/OrganizationIntegrationForm/OrganizationIntegrationForm.js, src/OrganizationIntegration/OrganizationIntegrationForm/SchedulingForm/SchedulingForm.js, src/OrganizationIntegration/OrganizationIntegrationView/SchedulingView/SchedulingView.js
https://issues.folio.org/browse/UIORGS-338
Convert time value to UTC before sent to BE
While …
=> UIORGS-338 Fix timezone in organization integration config for "Daily" schedule period

CHANGELOG.md, src/Organizations/Organizations.js, src/Organizations/OrganizationsList/OrganizationsList.js
https://issues.folio.org/browse/UIORGS-323
Provide `resetFilters` state on location change to use hook for reset active filters
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
=> UIORGS-323 No results found shown after return to search page

CHANGELOG.md, src/Organizations/OrganizationForm/OrganizationContactPeopleForm/__snapshots__/OrganizationContactPeopleForm.test.js.snap, src/Organizations/OrganizationForm/OrganizationInterfacesForm/__snapshots__/OrganizationInterfacesForm.test.js.snap, src/Organizations/OrganizationsList/OrganizationsList.js, src/Organizations/OrganizationsList/OrganizationsList.test.js, src/contacts/ViewContact/__snapshots__/ViewContact.test.js.snap
https://issues.folio.org/browse/UIORGS-328 …
=> UIORGS-328 Results List | Hyperlink one column to improve accessibility

src/Organizations/OrganizationForm/OrganizationContactPeopleForm/__snapshots__/OrganizationContactPeopleForm.test.js.snap, src/Organizations/OrganizationForm/OrganizationInterfacesForm/__snapshots__/OrganizationInterfacesForm.test.js.snap, src/contacts/ViewContact/__snapshots__/ViewContact.test.js.snap
=> Update jest snapshots

src/common/components/Credentials/Credentials.css
=> UIORGS-352 Fix CSS bundle issue with semicolon

package.json
CI tests failed due to absence of `@babel/plugin-private-property-in-object` dependency: …
=> Add missing `@babel/plugin-private-property-in-object` dependency

CHANGELOG.md, src/Organizations/OrganizationCreate/OrganizationCreate.js, src/Organizations/OrganizationEdit/OrganizationEdit.js, src/Organizations/OrganizationForm/OrganizationContactPeopleForm/OrganizationContactPeopleList.js, src/Organizations/OrganizationForm/OrganizationInterfacesForm/OrganizationInterfacesList.js, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-375 …
=> UIORGS-375 No pop-up message when creating or editing an organization.

CHANGELOG.md, package.json, src/Organizations/OrganizationForm/OrganizationContactPeopleForm/__snapshots__/OrganizationContactPeopleForm.test.js.snap, src/Organizations/OrganizationForm/OrganizationInterfacesForm/__snapshots__/OrganizationInterfacesForm.test.js.snap, src/contacts/ViewContact/__snapshots__/ViewContact.test.js.snap
Use plugins compatible with the requested version of stripes (v9).
Refs [UIORGS-404](https://issues.folio.org/browse/UIORGS-404)
=> UIORGS-404 bump optional plugins to compatible versions

CHANGELOG.md, src/Organizations/OrganizationDetails/OrganizationBankingInfo/BankingInformationCard/BankingInformationCard.js, src/Organizations/OrganizationDetails/OrganizationBankingInfo/BankingInformationCard/BankingInformationCard.test.js, src/Organizations/OrganizationDetails/OrganizationBankingInfo/BankingInformationCard/index.js, src/Organizations/OrganizationDetails/OrganizationBankingInfo/OrganizationBankingInfo.js, src/Organizations/OrganizationDetails/OrganizationBankingInfo/OrganizationBankingInfo.test.js, src/Organizations/OrganizationDetails/OrganizationBankingInfo/index.js, src/Organizations/OrganizationDetails/OrganizationDetails.js, src/Organizations/OrganizationDetails/OrganizationDetails.test.js, src/Organizations/OrganizationDetails/OrganizationDetailsContainer.js, src/Organizations/OrganizationDetails/OrganizationDetailsContainer.test.js
https://issues.folio.org/browse/UIORGS-389
- Implement components for viewing banking information details of an organization;
- Add unit tests.
https://github.com/folio-org/ui-organizations/assets/88109087/c2e6b5f2-550f-4383-ac85-e79381dc7d95
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> UIORGS-389 Implement organization's banking information details view

CHANGELOG.md, package.json, src/Organizations/OrganizationDetails/OrganizationDetails.js, src/Organizations/OrganizationForm/OrganizationBankingInfoForm/OrganizationBankingInfoForm.js, src/Organizations/OrganizationForm/OrganizationForm.js, translations/ui-organizations/en.json
https://issues.folio.org/browse/UIORGS-388
Some libraries want to store information specific to banks and bank accounts within FOLIO. This information needs to be associated with Organizations, but requires a discrete level of permissions in order to access.
Define new permission sets to protect banking information operations: view, edit, create, and delete. Protect appropriate actions by new permissions.
- Are the JIRAs under …
=> UIORGS-388 Protection of viewing and changes of banking information by permissions

package.json
https://issues.folio.org/browse/UIORGS-390
Init PR: #580 
Add missed perm to get bank account types …
=> UIORGS-390 Add permission to view banking account types

src/Organizations/OrganizationDetails/OrganizationDetails.js, src/Organizations/OrganizationForm/OrganizationForm.js
https://issues.folio.org/browse/UIORGS-397
Users without access to privileged donors' information shouldn't see related accordions on the organization view/form.
Continue of #592
https://github.com/folio-org/ui-organizations/assets/88109087/b11a907e-2820-4bde-b15d-505080bec432
Ideally all of the PRs involved in breaking changes would be merged in the same …
=> UIORGS-397 Hide accordion if a user doesn't have perms to view privileged donors

src/Organizations/OrganizationDetails/OrganizationDetails.js, src/Organizations/OrganizationForm/OrganizationForm.js
https://issues.folio.org/browse/UIORGS-397?focusedCommentId=199619&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-199619
Privileged donor info should be visible for organizations that are not a vendor as well.
https://github.com/folio-org/ui-organizations/assets/88109087/b0697501-526b-4b90-9fd7-3b975e762d35
Ideally all of the …
=> UIORGS-397 Enable privileged donors for non-vendor organization

src/contacts/EditContact/util.js
https://issues.folio.org/browse/UIORGS-397
There is an issue after creating a new privileged contact for an organization: instead of updating the privileged donors list common contact people are updated.
https://github.com/folio-org/ui-organizations/assets/88109087/f65c57b2-036c-494d-9ec7-3e7943c03dc0
Ideally all of the PRs involved in breaking changes …
=> UIORGS-397 Update the correct field in the organization when creating a new privileged contact

CHANGELOG.md, src/OrganizationIntegration/OrganizationIntegrationForm/__snapshots__/OrganizationIntegrationForm.test.js.snap, src/Organizations/OrganizationForm/OrganizationAccountsForm/__snapshots__/OrganizationAccountsForm.test.js.snap, src/Organizations/OrganizationForm/OrganizationAgreementsForm/__snapshots__/OrganizationAgreementsForm.test.js.snap, src/Organizations/OrganizationForm/OrganizationSummaryForm/__snapshots__/OrganizationSummaryForm.test.js.snap, src/Organizations/useBankingInformationManager.js, src/common/hooks/useOrganizationBankingInformation/useOrganizationBankingInformation.js, src/contacts/EditContact/__snapshots__/EditContact.test.js.snap, src/interfaces/EditInterface/__snapshots__/EditInterface.test.js.snap, test/jest/__mock__/index.js, test/jest/__mock__/resizeObserver.mock.js
https://issues.folio.org/browse/UIORGS-418
Protect fetch and update of banking information from a user without special permissions.
https://github.com/folio-org/ui-organizations/assets/88109087/bd3825b6-070a-44b7-bad2-d9f045ddb290 …
=> UIORGS-418 Suppress banking information management for unauthorized user

package.json, src/OrganizationIntegration/OrganizationIntegrationForm/__snapshots__/OrganizationIntegrationForm.test.js.snap, src/OrganizationIntegration/OrganizationIntegrationView/__snapshots__/OrganizationIntegrationView.test.js.snap, src/Organizations/OrganizationForm/OrganizationVendorInfoForm/__snapshots__/OrganizationVendorInfoForm.test.js.snap, src/Organizations/OrganizationForm/__snapshots__/OrganizationForm.test.js.snap, src/contacts/EditContact/__snapshots__/EditContact.test.js.snap, src/contacts/ViewContact/__snapshots__/ViewContact.test.js.snap
=> UIORGS-417 add missed permissions

CHANGELOG.md, src/Organizations/OrganizationsList/OrganizationsList.js, src/contacts/EditContact/__snapshots__/EditContact.test.js.snap, translations/ui-organizations/en.json
https://folio-org.atlassian.net/browse/UIORGS-421
https://github.com/folio-org/ui-organizations/assets/88109087/5ab560e5-116c-4105-8f28-2c65244ce480 …
=> UIORGS-421 UX Consistency > Search results > Update HTML page title with search term entered

package.json
Bump up `stripes-acq-components` version in package.json to `~5.1.0`
=> Bump up `stripes-acq-components` version in package.json to `~5.1.0`

package.json
=>  UIORGS-193 missed permissions

src/Organizations/OrganizationVersion/components/OrganizationSummaryVersionView/OrganizationSummaryVersionView.js, src/Organizations/OrganizationVersion/hooks/useSelectedOrganizationVersion/useSelectedOrganizationVersion.js, src/Organizations/OrganizationVersion/hooks/useSelectedOrganizationVersion/useSelectedOrganizationVersion.test.js
https://issues.folio.org/browse/UIORGS-356
Fixes for #658 
https://github.com/user-attachments/assets/1b2f83c1-0b2e-43ba-8eb1-0664da76b98e …
=> UIORGS-356 Fix aliases version field

src/Organizations/OrganizationVersion/components/OrganizationSummaryVersionView/OrganizationSummaryVersionView.js, src/Organizations/OrganizationVersion/hooks/useSelectedOrganizationVersion/useSelectedOrganizationVersion.js, src/Organizations/OrganizationVersion/hooks/useSelectedOrganizationVersion/useSelectedOrganizationVersion.test.js
https://folio-org.atlassian.net/browse/UIORGS-356
Use the common hook to resolve reference data value.
Fixes https://github.com/folio-org/ui-organizations/pull/658;
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
=> UIORGS-356 Properly display mapped ref values

src/OrganizationIntegration/OrganizationIntegrationCreate/OrganizationIntegrationCreate.js, src/OrganizationIntegration/OrganizationIntegrationForm/IntegrationInfoForm/IntegrationInfoForm.js, src/OrganizationIntegration/constants.js
https://folio-org.atlassian.net/browse/UIORGS-442
https://github.com/user-attachments/assets/c456da45-3c2f-41e8-89ab-a2a7d1855e86
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
=> UIORGS-442 Change export type on integration type change

CHANGELOG.md, package.json
https://folio-org.atlassian.net/browse/UIORGS-459
https://folio-org.atlassian.net/browse/UIORGS-460
=> UIORGS-459 UIORGS-460 Migrate react-intl and stripes dependencies

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, src/OrganizationIntegration/OrganizationIntegrationForm/EdiForm/EdiForm.js, src/OrganizationIntegration/OrganizationIntegrationForm/FtpForm/FtpForm.js, src/OrganizationIntegration/OrganizationIntegrationForm/IntegrationInfoForm/IntegrationInfoForm.js, src/OrganizationIntegration/OrganizationIntegrationForm/SchedulingForm/SchedulingForm.js, src/OrganizationIntegration/utils.js
https://folio-org.atlassian.net/browse/UIORGS-468
To implement conditional validation correctly in `final-form`, we should rely on the current form values passed to the `validate` function of the `Field` component.
To avoid code duplication, creating a validator factory that returns either a validator (if the condition is met) or `undefined` (to skip validation) should be implemented.
https://github.com/user-attachments/assets/68740eb8-c97e-4d6b-af30-cc78d9ff18fd
- Do JIRAs …
=> UIORGS-468 Improve organization integration form fields validation
